INSERT INTO CRITERIA (CRIID,CRICODE,CRITARGET,CRITABLETOSEARCH,CRICOLUMNTOSEARCH,CRILANDESCRIPTIONCOLUMN,CRIFUNCTION,CRIVALUETYPE,CRIFILTERCLAUSE,CRIPARAMETER,CRITABLESETTING,CRITARGETTABLE,CRITARGETCOLUMN,CRIFLAGCASSIOPAE,CRITABLETYPE) 
VALUES (seq_CRIID.NEXTVAL,'JALCODEDVCLT','AVDOSS',null,null,null,'PAV4_CRITERIA.F_GET_INSTRUCTION_EXCUTE','BOOLEAN',null,null,null,null,null,null,null);
COMMIT ;
SELECT * FROM CRITERIA ORDER BY CRIID DESC;----8533 CE CRIID VA ETRE INSRRER DANS LA COLONNE CRIIDFIRST DE LA TABLE RULE
Insert into LANCRITERIA (LANCODE,CRIID,CRILABEL) 
values ('FR','8533','Exuction de l''instruction ');
INSERT INTO RULE (RULID,RULCODE,RULTARGET,RULOPERATOR,RULLOWERLIMIT,RULUPPERLIMIT,RULSTATUS,CRIIDFIRST,RULIDFIRST,RULIDSECOND,CRIIDSECONDMAX,CRIIDSECONDMIN,RULTYPE,RULFLAGCASSIOPAE,RULGROUP) 
values (seq_RULID.NEXTVAL,'EXISTJALONDVCLT','AVDOSS','=','TRUE',null,'1','8533',null,null,null,null,'LOGICAL',null,null);
commit ;
SELECT * FROM RULE ORDER BY RULID DESC ;---3007181 CE RULID VA ETRE INSRER DANS LES TABLES LANRULE AND LKFORRUL
INSERT INTO 
LANRULE (RULID,LANCODE,RULLABEL) 
values ('3007181','FR','JALON DVCLT');
commit ; 
 INSERT INTO LKFORRUL (FORID,RULID,FRUPRIORITY,FRULINKTYPE)
 VALUES (50015,'3007181',null,null);
  INSERT INTO LKFORRUL (FORID,RULID,FRUPRIORITY,FRULINKTYPE)
 VALUES (50014,'3007181',null,null);
 COMMIT ;