




Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT)
values ('CAFV','SGMLEA','CAFV',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('CASGL','SGMLEA','CECOM',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('CASGL','SGMLEA','CEPRO',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('CLICOM','SGMLEA','Sales',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('CLIPRO','SGMLEA','Sales',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('COMSGL','SGMLEA','COMPRO',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('COMSGL','SGMLEA','COMCOM',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('COMSGLEST','SGMLEA','CEST',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('COMSGLESTGE','SGMLEA','CESTGE',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('COMSGLNORD','SGMLEA','CNORD',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('COMSGLSUD','SGMLEA','CSUD',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('DA','SGMLEA','DASGMA',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('DGASGL','SGMLEA','DGSGL',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('DGSGL','SGMLEA','DGSGL',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('RISQ','SGMLEA','ANA',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('RISQSGL','SGMLEA','DRSGL',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('RMCP','SGMLEA','RMCP',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('U_SOGEC','SGMLEA','SOGC',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('U_VENDOR','SGMLEA','VDR',null,'1');
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT) values ('U_VENDOR2','SGMLEA','VDR',null,'1');

--------------------------------------------


Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','GRPORFI',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','GEST',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','FACT',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','ENG',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','DIR',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','DAF',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','IT',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CECOM',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CAFV',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CEPRO',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CPRO',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CCOM',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','COMCOM',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','COMPRO',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','RMCP',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CC PRO',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','DA',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CC PART',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','DCA',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','RM',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CE',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CCOMN',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CCOMS',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CCOMEST',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CCOMGE',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','Sales',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CHARCLI',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','ANA',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','DGSGL',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','DRSGL',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','DGSGMA',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','DRSGMA',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','DRIBF',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CCSGMA',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','SOGC',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','VDR',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','WEB',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','DASGMA',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CSUD',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CNORD',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CESTGE',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('METIER','CEST',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('JOB','CECOM',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('JOB','CEPRO',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('JOB','COMCOM',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('JOB','COMPRO',null);
Insert into TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) values ('JOB','DASGMA',null);

--------------------------------


Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','REC','EN','Recouvrement',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','ANALYS','EN','Analyste',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','MO','EN','Middle office',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','TRES','EN','Trésorerie',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','REAL','EN','Réalisation',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','GEST','EN','Gestion',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','FACT','EN','Facturation',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','ENG','EN','Engagement',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','DIR','EN','Direction',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CTRL','EN','Contrôle',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CPTA','EN','Comptabilité',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CTX','EN','Contentieux',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','ACH','EN','Achat',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','DAF','EN','Diarection Adm & Fina',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','IT','EN','IT',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','GEST','FR','Gestion',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','FACT','FR','Facturation',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','ENG','FR','Engagement',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','DIR','FR','Direction',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','DAF','FR','Direction Adm & Fina',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','IT','FR','IT',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','SUIVEUR','EN','Chargé d''affaire',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','GRPORFI','FR','Orfi Group',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','GRPORFI','EN','Orfi Group',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','DA','FR','Directeur d''agence',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CC PART','FR','Chargé de clientèle particulier',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','DCA','FR','Directeur centre d''affaire',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','RM','FR','Relationship Manager',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CC PRO','FR','Chargé de clientèle pro',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CECOM','FR','Chargé d‘études',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CAFV','FR','Chargé financement de vente',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CEPRO','FR','Chargé d''étude CLIPRO',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CE','FR','Chargé d‘études',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','DASGMA','FR','Directeur Agence',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','RMCP','FR','Responsable du Marché de la Clientèle Pro',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','Sales','FR','Sales',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','Sales','EN','Sales',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CHARCLI','FR','Chargé Clientèle',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','ANA','FR','Analyste de risque',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','DGSGL','FR','Direction Général Sogelease',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','DRSGL','FR','Direction Risque Sogelease',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','DGSGMA','FR','Direction Général SGMA',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','DRSGMA','FR','Direction Risque SGMA',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','DRIBF','FR','Direction Risque IBF',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CCSGMA','FR','Charge clientèle SGMA',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','SOGC','FR','SogeContact',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','VDR','FR','Vendors',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','WEB','FR','Utilisateur Web',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CSUD','FR','Commercial SGLM SUD',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CNORD','FR','Commercial SGLM NORD',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CESTGE','FR','Commercial CASA EST Grande Entreprise',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','CEST','FR','Commercial CASA EST',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('JOB','CECOM','FR','Chargé d"étude SGL CLICOM',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('JOB','CEPRO','FR','Chargé d"étude SGL CLICPRO',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('JOB','COMCOM','FR','Commercial SGL CLICOM',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('JOB','COMPRO','FR','Commercial SGL CLIPRO',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('JOB','DASGMA','FR','Directeur Agence',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('JOB','RMCP','FR','Responsable du Marché de la Clientèle Pro',null);

Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','COMCOM','FR','Commercial SGL CLICOM',null);
Insert into LANTUSPARAM (TUSNOM,TUPCODE,LANCODE,TUPLIBELLE,TUPHELPTEXT) values ('METIER','COMPRO','FR','Commercial SGL CLIPRO',null);


Commit;