---- Création GROUPES
Insert into GROUPE (GROCODE,GROINTITULE) values ('CC_COM','Chargé Clientèle Clicom');
Insert into GROUPE (GROCODE,GROINTITULE) values ('DA','Directeur d’Agence');
-------SELECT * FROM GROUPE WHERE GROCODE IN ('CC_PRO', 'CC_COM', 'DA');
COMMIT;
-------SELECT * FROM UTILISATEUR WHERE UTICODE IN ('CLIPRO', 'DA', 'CLICOM', 'TW');

---- Création UTILISATEURS relatifs aux GROUPES
Insert into UTILISATEUR (UTICODE,UGECODE,GROCODE,UTINOM,UTIPRENOM,UTIFLAGINACTIF,UTITELECOM,UTIFLAGPASSWORD,UTIDTUPD,UTIWHODUNNIT,UTICRC,UTICODESUBSTITUTE,UTIPWD,UTIPWDDTCHGD,UTILOCKED,UTIATTEMPTS,UTILOCKTIME,UTILDAPREFERENCE,UTIFLAGPERMANENT)
values ('DA','SGM','DA','Agence','Directeur',null,null,'0',to_date('09/02/21','DD/MM/RR'),'ORFI',null,null,'ead0242d347decdb071818cedf073c1f',to_date('09/02/21','DD/MM/RR'),'N','0',null,null,'0');
Insert into UTILISATEUR (UTICODE,UGECODE,GROCODE,UTINOM,UTIPRENOM,UTIFLAGINACTIF,UTITELECOM,UTIFLAGPASSWORD,UTIDTUPD,UTIWHODUNNIT,UTICRC,UTICODESUBSTITUTE,UTIPWD,UTIPWDDTCHGD,UTILOCKED,UTIATTEMPTS,UTILOCKTIME,UTILDAPREFERENCE,UTIFLAGPERMANENT)
values ('CLICOM','SGM','CC_COM','CHARGE','CLICOM',null,null,'0',to_date('26/01/21','DD/MM/RR'),'CLICOM',null,null,'9f92f58aed0bf2c284b35c90f631f280',to_date('26/01/21','DD/MM/RR'),'N','0',null,null,'1');
Insert into UTILISATEUR (UTICODE,UGECODE,GROCODE,UTINOM,UTIPRENOM,UTIFLAGINACTIF,UTITELECOM,UTIFLAGPASSWORD,UTIDTUPD,UTIWHODUNNIT,UTICRC,UTICODESUBSTITUTE,UTIPWD,UTIPWDDTCHGD,UTILOCKED,UTIATTEMPTS,UTILOCKTIME,UTILDAPREFERENCE,UTIFLAGPERMANENT)
values ('TW','SGM','CC_PRO','WILL','TEAM',null,null,'0',to_date('16/09/20','DD/MM/RR'),'TW',null,null,'b525be338694e258f40dbbd6ef967696',to_date('16/09/20','DD/MM/RR'),'N','0',null,null,'1');
COMMIT;
-------SELECT * FROM UTILISATEUR WHERE GROCODE IN ('CC_PRO', 'CC_COM', 'DA');

---- Affectation des droits aux GROUPES créés
---Insert into LKGROTMFDROIT (TMOMODULE,TMFFONCTION,GROCODE,GFDCREER,GFDMODIFIER,GFDSUPPRIMER,GFDVOIR,DEVCODE,GFDMTPLAFOND) values ('ACTEUR','EVA_JASPER','CC_PRO',null,'1','1','1',null,null);
Insert into LKGROTMFDROIT (TMOMODULE,TMFFONCTION,GROCODE,GFDCREER,GFDMODIFIER,GFDSUPPRIMER,GFDVOIR,DEVCODE,GFDMTPLAFOND) values ('ACTEUR','EVACT_RIBREMP','CC_COM','0','0','0','0',null,null);
---Insert into LKGROTMFDROIT (TMOMODULE,TMFFONCTION,GROCODE,GFDCREER,GFDMODIFIER,GFDSUPPRIMER,GFDVOIR,DEVCODE,GFDMTPLAFOND) values ('ACTEUR','EVA_JASPER','CC_COM',null,'1','1','1',null,null);
Insert into LKGROTMFDROIT (TMOMODULE,TMFFONCTION,GROCODE,GFDCREER,GFDMODIFIER,GFDSUPPRIMER,GFDVOIR,DEVCODE,GFDMTPLAFOND) values ('ACTEUR','EVACT_RIBREMP','CC_PRO','0','0','0','0',null,null);
Insert into LKGROTMFDROIT (TMOMODULE,TMFFONCTION,GROCODE,GFDCREER,GFDMODIFIER,GFDSUPPRIMER,GFDVOIR,DEVCODE,GFDMTPLAFOND) values ('ACTEUR','EVACT_RIBREMP','DA','0','0','0','0',null,null);
Insert into LKGROTMFDROIT (TMOMODULE,TMFFONCTION,GROCODE,GFDCREER,GFDMODIFIER,GFDSUPPRIMER,GFDVOIR,DEVCODE,GFDMTPLAFOND) values ('ACTEUR','EVACT_ADRREMP','CC_COM','0','0','0','0',null,null);
Insert into LKGROTMFDROIT (TMOMODULE,TMFFONCTION,GROCODE,GFDCREER,GFDMODIFIER,GFDSUPPRIMER,GFDVOIR,DEVCODE,GFDMTPLAFOND) values ('ACTEUR','EVACT_ADRREMP','CC_PRO','0','0','0','0',null,null);
Insert into LKGROTMFDROIT (TMOMODULE,TMFFONCTION,GROCODE,GFDCREER,GFDMODIFIER,GFDSUPPRIMER,GFDVOIR,DEVCODE,GFDMTPLAFOND) values ('ACTEUR','EVACT_ADRREMP','DA','0','0','0','0',null,null);
Insert into LKGROTMFDROIT (TMOMODULE,TMFFONCTION,GROCODE,GFDCREER,GFDMODIFIER,GFDSUPPRIMER,GFDVOIR,DEVCODE,GFDMTPLAFOND) values ('ACTEUR','EVACT_MRAIS','CC_COM','0','0','0','0',null,null);
Insert into LKGROTMFDROIT (TMOMODULE,TMFFONCTION,GROCODE,GFDCREER,GFDMODIFIER,GFDSUPPRIMER,GFDVOIR,DEVCODE,GFDMTPLAFOND) values ('ACTEUR','EVACT_MRAIS','CC_PRO','0','0','0','0',null,null);
Insert into LKGROTMFDROIT (TMOMODULE,TMFFONCTION,GROCODE,GFDCREER,GFDMODIFIER,GFDSUPPRIMER,GFDVOIR,DEVCODE,GFDMTPLAFOND) values ('ACTEUR','EVACT_MRAIS','DA','0','0','0','0',null,null);
Insert into LKGROTMFDROIT (TMOMODULE,TMFFONCTION,GROCODE,GFDCREER,GFDMODIFIER,GFDSUPPRIMER,GFDVOIR,DEVCODE,GFDMTPLAFOND) values ('ACTEUR','EVACT_PHAREMP','CC_COM','0','0','0','0',null,null);
Insert into LKGROTMFDROIT (TMOMODULE,TMFFONCTION,GROCODE,GFDCREER,GFDMODIFIER,GFDSUPPRIMER,GFDVOIR,DEVCODE,GFDMTPLAFOND) values ('ACTEUR','EVACT_PHAREMP','CC_PRO','0','0','0','0',null,null);
Insert into LKGROTMFDROIT (TMOMODULE,TMFFONCTION,GROCODE,GFDCREER,GFDMODIFIER,GFDSUPPRIMER,GFDVOIR,DEVCODE,GFDMTPLAFOND) values ('ACTEUR','EVACT_PHAREMP','DA','0','0','0','0',null,null);
COMMIT;
-------SELECT * FROM LKGROTMFDROIT WHERE GROCODE IN ('CC_PRO', 'CC_COM', 'DA');


