--------------------------------------------------------
--  Fichier créé - jeudi-septembre-23-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View V_ACTEUR_FO_2
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_ACTEUR_FO_2" ("ADOSID", "DT_CREA_ACTEUR", "Nom ClientB", "Titre CLTB", "Code ClientB", "Capital Social CLTB", "List BANK ACT", "Code SEGMENT CLIENT", "CODE RC", "Patent", "Voie CLTB", "PAYS CLT", "CJULIBELLE CLTB", "ADRESSE CLT2", "VILLE CLTB", "ADRESSE CLT FA2", "Email ClientB", "LIVADRVOIE CLTB", "LIVADRLIEUDIT CLTB", "LIVADRCODEPOST CLTB", "LIVADRCOPVILLE CLTB", "ADRCOPVILLE CLTB", "ACTCODE CLTB", "CodePoste CLTB", "Lieu CLTB", "Ville CLTB", "CPOSUBREGION CLTB", "SIRET CLTB", "MODREG CLTB", "LIBMODREG CLTB", "BNQCOMPTENUM CLTB", "RIB CLT", "BNQLIBELLE CLTB", "Adresse siege CLT", "Adresse ClientB", "Adresse facturation CltB", "Type CLTB", "NumRCM CLTB", "VILLERC CLTB", "TypeID CLTB", "LIBTypeID CLTB", "NumID CLTB", "DateID CLTB", "ACTID CLTB", "TEL CLT", "FAX CLT", "MOB CLT", "CLTACTIVITE", "SIRET FRS", "Nom FournB", "Titre FournB", "Code FournB", "Capital Social FournB", "Voie FRSB", "CodePoste FRSB", "Lieu FRSB", "VILLE FRSB", "CPOSUBREGION FRSB", "ACTID FRSB", "Type FRSB", "ACTLIBCOURT FRSB", "CJULIBELLE FRSB", "VILLERC FRSB", "NumRCM FRSB", "TypeID FRSB", "LIBTypeID FRS", "NumID FRSB", "DateID FRSB", "GARANTTITRE", "GARANTNATUREB", "GARANTACTNOMB", "GARANTACTLIBB", "Capital Social GAR", "CODEGARNATIDB", "GARANTNATIDB", "GARANTNUMIDB", "GARANTDATEIDB", "GARANTNUMRCB", "GARANTVILLERCB", "GARANTGACODEB", "GARANTGALIBELLEB", "GARANTGADESCRIPB", "GARANTMTB", "GARACTYPEB", "NBGARANTB", "ACTID GAR", "GARANTACTCODE", "SIRET GAR", "CJULIBELLEGAR", "GARANTADRVOIE", "ADRESSE GAR2", "GARANTADRLIEUDIT", "PAYS GARANT", "GARANTADRCODEPOST", "GARANTADRCOPVILLE", "PERIODICITEB", "ACTID AGB", "VILLE AGB", "TITREAGB", "NOMAGB", "PRENOMAGB", "ACTCODEAGENCEB", "SIGNATAIRE AG", "NOMAGENCE", "AGVILLEB", "DATEJOUR", "DEMANDEFINB", "INTERNOMAG", "INTERPRENOMAG", "TELAG", "MAILAG", "MOBAG", "FAXAG", "Encours CTR ACTIF", "MT_INI_CTR_ACTIF", "Date encouts client CTR ACTIF", "Encours CTR ENG", "MT_INI_CTR_ENG", "Date encouts client CTR ENG", "Impaye_Acteur", "DT_Impaye_Acteur", "NB_CTR_ECHU", "MTINV_CTR_ECHU", "Date encouts client CTR ECH", "ROLE", "SIGNATAIRE", "DPRVERSION") AS 
  SELECT
       DPR.DOSID AS "ADOSID",
       ACT.ACTDTCREAT "DT_CREA_ACTEUR" ,
       NVL (PAV4_JASPER_FO.F_GET_ACTOR_NAME2 ( DPR.DOSID, 'CLIENT'),' ') AS "Nom ClientB",
       NVL (PAV4_JASPER_FO.F_GET_TITLE_ACTEUR (ACTE.ACTID, DPR.DOSID, 'CLIENT'), ' ') AS "Titre CLTB",
       NVL (PAV4_JASPER_FO.F_GET_CODE_ACTEUR (ACTE.ACTID, DPR.DOSID, 'CLIENT'),' ') AS "Code ClientB",
       NVL (ACT.ACTCAPITAL,'0') AS "Capital Social CLTB",
       PAV4_JASPER_FO.F_GET_LIST_BANK_ACT (ACT.ACTID)"List BANK ACT" ,
       substr(PAV4_jasper_Fo.F_GET_CC_ACT(ACT.ACTID,'CMBCCHSID82'),1,5) "Code SEGMENT CLIENT",
        PAV4_jasper_Fo.F_GET_CC_ACT(ACT.ACTID,'TFDCCHSID805') "CODE RC",
        PAV4_jasper_Fo.F_GET_CC_ACT(ACT.ACTID,'TFDCCHSID197') "Patent",

       NVL (ADR.ADRVOIE,' ') AS "Voie CLTB",
       Nvl(UPPER(LP.PAYLIBELLE),' ') "PAYS CLT",
       NVL(LCJ.CJULIBELLE,' ') AS "CJULIBELLE CLTB",
       PAV4_JASPER_FO.F_GET_ACTOR_ADRESSE_V2 ( DPR.DOSID,'CLIENT','SIEGE') as "ADRESSE CLT2",
       NVL(NVL (COP.CPOSUBREGION, ADR.ADRVILLE),' ') AS "VILLE CLTB",
       NVL(PAV4_JASPER_FO.F_GET_ACTEUR_ADRESSE_V2(DPR.DOSID, 'CLIENT','FACTURATION'),' ')AS "ADRESSE CLT FA2",
       NVL (PAV4_JASPER_FO.F_GET_ACTOR_TELECOM (DPR.DOSID, 'CLIENT', 'NET'),' ')  AS "Email ClientB",
       NVL (ADR1.ADRVOIE ,' ')  AS "LIVADRVOIE CLTB",
       NVL (ADR1.ADRLIEUDIT,' ')   AS "LIVADRLIEUDIT CLTB",
       NVL (ADR1.ADRCODEPOST,' ')  AS "LIVADRCODEPOST CLTB",
       NVL (COP1.CPOSUBREGION,' ')  AS "LIVADRCOPVILLE CLTB",
       NVL (COP1.CPOSUBREGION,' ')   AS "ADRCOPVILLE CLTB",
       ACT.ACTCODE  AS "ACTCODE CLTB",
       NVL (ADR.ADRCODEPOST,' ') AS "CodePoste CLTB",
       NVL ( ADR.ADRLIEUDIT,' ')  AS "Lieu CLTB",
       Nvl(ADR.adrville,' ') AS "Ville CLTB",
       NVL (COP.CPOSUBREGION,' ') AS "CPOSUBREGION CLTB",
       NVL (ACT.ACTSIRET,' ')    AS "SIRET CLTB",
       NVL (ACTE.TMPCODEENC, ' ') AS "MODREG CLTB",
       NVL (DECODE (ACTE.TMPCODEENC,'EFFET', 'Effets acceptés','PRLAUTO', 'Titre de crédit accepté',' '),' ') AS "LIBMODREG CLTB",
       NVL ((SELECT RIB.RIBCOMPTE FROM RIB, DPRACTEUR DP WHERE     RIB.RIBID = DP.RIBIDENC  AND DP.ROLCODE = 'CLIENT'
          AND DP.DOSID = DPR.DOSID AND DP.DPRVERSION=DPR.DPRVERSION ),' ') AS "BNQCOMPTENUM CLTB",
       Nvl(PAV4_JASPER_FO.F_GET_NUM_COMPTE_BANCAIRE(DPR.DOSID,'CLIENT') ,' ') as "RIB CLT",
       PAV4_JASPER_FO.F_GET_BANK_NAME(DPR.DOSID,'CLIENT') || ' ' || PAV4_JASPER_FO.F_GET_AGENCE_BANCAIRE(DPR.DOSID,'CLIENT') AS "BNQLIBELLE CLTB",
       NVL (PAV4_JASPER_FO.F_GET_ACTOR_ADRESSE2 (DPR.DOSID ,'CLIENT','SIEGE'), ' ') AS "Adresse siege CLT",
       NVL (PAV4_JASPER_FO.F_GET_ACTOR_ADRESSE (DPR.DOSID, 'CLIENT'), ' ') AS "Adresse ClientB",
       NVL (PAV4_JASPER_FO.F_GET_ACTOR_ADRESSE (DPR.DOSID,'CLIENT','FACTURATION'), ' ') AS "Adresse facturation CltB",
       decode(ACT.ACTTYPE,'P','PART',ACT.ACTTYPE) AS "Type CLTB",
       NVL ( ACT.ACTNUMRCM,' ') AS "NumRCM CLTB",
       NVL ((SELECT DISTINCT A.CVASTRINGVALUE   FROM cchvalue A WHERE     A.cchsid = 'TFDCCHSID1594' AND A.actid = ACTE.ACTID
                  AND A.CVAID =(SELECT MAX (CVAID) FROM cchvalue WHERE     cchsid = 'TFDCCHSID1594' AND actid = ACTE.ACTID AND ACTE.ROLCODE='CLIENT')),' ') AS "VILLERC CLTB",
       NVL ( (SELECT MAX (CVASTRINGVALUE) FROM CCHVALUE  WHERE CCHSID = 'CMBCCHSID1574' AND ACTID = ACTE.ACTID AND ACTE.ROLCODE='CLIENT'),' ') AS "TypeID CLTB",
       NVL ( (SELECT DECODE(MAX (CVASTRINGVALUE),'CIN','de la Carte d''Identité Nationale','TITSEJ','du Titre de séjour','PASSP','du Passeport')  FROM CCHVALUE
               WHERE CCHSID = 'CMBCCHSID1574' AND ACTID = ACTE.ACTID AND ACTE.ROLCODE='CLIENT'),' ') AS "LIBTypeID CLTB",
      ACT.ACTEIN AS "NumID CLTB",
        (SELECT To_Char(MAX (CVADTVALUE),'DD/MM/YYYY')  FROM CCHVALUE  WHERE CCHSID = 'TFDCCHSID1695' AND ACTID = ACTE.ACTID )  AS "DateID CLTB",
       ACTE.ACTID AS "ACTID CLTB",
       PAV4_JASPER_FO.F_GET_TELECOM_ACT(ACTE.ACTID,'TEL') as "TEL CLT",
       NVL( PAV4_JASPER_FO.F_GET_TELECOM_ACT(ACTE.ACTID,'FAX'),' ') as "FAX CLT",
       PAV4_JASPER_FO.F_GET_TELECOM_ACT(ACTE.ACTID,'MOB') as "MOB CLT",
       NAF.NAFLIBELLE AS  "CLTACTIVITE",
       --  (NVL((select F_MT_FACTIMP_CLT(ACTE.ACTID) from dual),0) ) AS "MT_IMP_CLT",
       ----------------FOURNISSEUR------------------------
	     NVL (ACT.ACTSIRET,' ') AS "SIRET FRS",
       NVL (PAV4_JASPER_FO.F_GET_ACTOR_NAME2 ( DPR.DOSID, 'FOURN'),' ') AS "Nom FournB",
       NVL (PAV4_JASPER_FO.F_GET_TITLE_ACTEUR (ACTE.ACTID, DPR.DOSID, 'FOURN'),' ') AS "Titre FournB",
       act.actcode  AS "Code FournB",
       NVL (ACT.ACTCAPITAL,'0') AS "Capital Social FournB",
       NVL (ADR.ADRVOIE,' ') AS "Voie FRSB",
       NVL (ADR.ADRCODEPOST, ' ') AS "CodePoste FRSB",
       NVL (ADR.ADRLIEUDIT,' ') AS "Lieu FRSB",
       NVL (ADR.ADRVILLE ,' ') AS "VILLE FRSB",
       NVL (COP.CPOSUBREGION,' ')  AS "CPOSUBREGION FRSB",
       ACTE.ACTID AS "ACTID FRSB",
       Nvl(decode(ACT.ACTTYPE,'EI','PART',ACT.ACTTYPE),' ') AS "Type FRSB",
       NVL (ACT.ACTLIBCOURT, ' ') AS "ACTLIBCOURT FRSB",
       NVL(SubStr(LCJ.CJULIBELLE,InStr(LCJ.CJULIBELLE,'-')+2,Length(LCJ.CJULIBELLE)),' ')     AS "CJULIBELLE FRSB",
       NVL ( (SELECT MAX (A.CVASTRINGVALUE) FROM cchvalue A  WHERE     A.cchsid = 'TFDCCHSID1594'  AND A.actid = ACTE.ACTID
                  AND A.CVAID = (SELECT MAX (CVAID) FROM cchvalue  WHERE     cchsid = 'TFDCCHSID1594' AND actid = ACTE.ACTID AND ACTE.ROLCODE='FOURN')),' ') AS "VILLERC FRSB",                                          -----ADD
       NVL (ACT.ACTNUMRCM,' ') AS "NumRCM FRSB",
       NVL ( (SELECT MAX (CVASTRINGVALUE)
                FROM CCHVALUE WHERE CCHSID = 'CMBCCHSID1574' AND ACTID = ACTE.ACTID),' ')  AS "TypeID FRSB",
       NVL ( (SELECT DECODE(MAX (CVASTRINGVALUE),'CIN','de la Carte d''Identité Nationale','TITSEJ','du Titre de séjour','PASSP','du Passeport')
                FROM CCHVALUE
               WHERE CCHSID = 'CMBCCHSID1574' AND ACTID = ACTE.ACTID AND ACTE.ROLCODE='FOURN'),' ')  AS "LIBTypeID FRS",
       NVL ( (SELECT MAX (CVASTRINGVALUE) FROM CCHVALUE  WHERE CCHSID = 'TFDCCHSID1676' AND ACTID = ACTE.ACTID AND ACTE.ROLCODE='FOURN'),' ')  AS "NumID FRSB",
       NVL ( (SELECT TO_CHAR (MAX (CVADTVALUE), 'DD/MM/YYYY') FROM CCHVALUE  WHERE CCHSID = 'TFDCCHSID1695' AND ACTID = ACTE.ACTID AND ACTE.ROLCODE='FOURN'),' ')  AS "DateID FRSB",
       ---------------GARANTIE---------
NVL((SELECT PAV4_JASPER_FO.F_TITREGARANT(ACTID) FROM ACTEUR WHERE ACTID=ACTE.ACTID and ACTE.ROLCODE='GARANT'),' ') GARANTTITRE,
       NVL ( ACT.CJUCODE, ' ') AS "GARANTNATUREB",
       ACT.ACTNOM AS "GARANTACTNOMB",
       NVL ( ACT.ACTLIBCOURT,' ')  AS "GARANTACTLIBB",
       NVL (ACT.ACTCAPITAL,'0')  AS "Capital Social GAR",
       nvl(PAV4_JASPER_FO.F_TYPEIDENTITEGARANT (ACTE.ACTID),' ') AS "CODEGARNATIDB" ,
       NVL (DECODE((PAV4_JASPER_FO.F_TYPEIDENTITEGARANT (ACTE.ACTID)),'CIN','de la Carte d''Identité Nationale','TITSEJ',' du Titre de séjour','PASSP','du Passeport'), ' ')
          AS "GARANTNATIDB",
       NVL (PAV4_JASPER_FO.F_NUMIDENTITEGARANT (ACTE.ACTID), ' ')
          AS "GARANTNUMIDB",
       NVL (PAV4_JASPER_FO.F_DTIDENTITEGARANT (ACTE.ACTID), SYSDATE) AS "GARANTDATEIDB",
       NVL ( ACT.ACTNUMRCM,' ')  AS "GARANTNUMRCB",
       NVL (PAV4_JASPER_FO.F_VILLERCGARANT (ACTE.ACTID), ' ') AS "GARANTVILLERCB",
        (SELECT Max(DGC.TGACODE) FROM PFIGUARANTEE DGC WHERE DGC.PFIID = PA_REQUETE_COMMUN.F_PROPOSITION_RETENUE (dpr.dosid,dpr.dprversion,NULL)
           AND DGC.ACTID=ACTE.ACTID AND ACTE.ROLCODE='GARANT') AS "GARANTGACODEB",
       NVL ( (SELECT MAX(TGALIBELLE)
             FROM lantgarantie
            WHERE     LANCODE = 'FR'
                  AND TGACODE =
                         (SELECT MAX (DGC.TGACODE)
                            FROM PFIGUARANTEE DGC
                           WHERE DGC.PFIID = PA_REQUETE_COMMUN.F_PROPOSITION_RETENUE (dpr.dosid,dpr.dprversion,NULL) AND ACTE.ROLCODE='GARANT' AND DGC.ACTID=ACTE.ACTID)),' ')
          AS "GARANTGALIBELLEB",
       NVL ( (SELECT MAX (DGC.PFGDESCRIPTION)
                FROM PFIGUARANTEE DGC
               WHERE DGC.PFIID = PA_REQUETE_COMMUN.F_PROPOSITION_RETENUE (dpr.dosid,dpr.dprversion,NULL)AND DGC.ACTID=ACTE.ACTID AND ACTE.ROLCODE='GARANT' ),' ')
          AS "GARANTGADESCRIPB",
       NVL ( (SELECT MAX (DGC.PFGMTGUARANTEE)
                FROM PFIGUARANTEE DGC
               WHERE DGC.PFIID = PA_REQUETE_COMMUN.F_PROPOSITION_RETENUE (dpr.dosid,dpr.dprversion,NULL) AND DGC.ACTID=ACTE.ACTID AND ACTE.ROLCODE='GARANT'),0)
          AS "GARANTMTB",
       NVL ( Decode(ACT.ACTTYPE,'EI','PART',ACT.ACTTYPE),' ') AS "GARACTYPEB",
       PAV4_JASPER_FO.F_NBGARANT (dpr.DOSID, DPR.DPRVERSION) AS "NBGARANTB",
       (ACTE.ACTID) AS "ACTID GAR",
	   ACT.ACTCODE  GARANTACTCODE,
	  NVL ( ACT.ACTSIRET,' ') AS "SIRET GAR",
    NVL(SubStr(LCJ.CJULIBELLE,InStr(LCJ.CJULIBELLE,'-')+2,Length(LCJ.CJULIBELLE)),' ') AS "CJULIBELLEGAR",
	    NVL (ADR.ADRVOIE,' ') GARANTADRVOIE,
   PAV4_JASPER_FO.F_GET_ACTOR_ADRESSE_V2 ( DPR.DOSID,'GARANT','SIEGE') as "ADRESSE GAR2",
		   NVL (ADR.ADRLIEUDIT,' ')  GARANTADRLIEUDIT,
          lp.PAYLIBELLE "PAYS GARANT",
		    NVL (ADR.ADRCODEPOST,' ')  GARANTADRCODEPOST,
		    NVL (ADR.ADRVILLE || ' ' || COP.CPOSUBREGION, ' ')  GARANTADRCOPVILLE,
       ----AGENCE-------
       null  AS "PERIODICITEB",
       AG.ACTID AS "ACTID AGB",
       NVL (SUBSTR (AG.ACTNOM, 14, 50),' ') AS "VILLE AGB",
      NULL AS "TITREAGB",
       NVL (PAV4_JASPER_FO.F_GET_NOM_AGENCE (AG.ACTID),' ') AS "NOMAGB",
       NULL  AS "PRENOMAGB",
       Nvl(AG.ACTCODE,' ') AS "ACTCODEAGENCEB",
   NVL ((PAV4_JASPER_FO.F_GET_ALL_CONTACTS_FO (DPR.DOSID,'AGENCE',AG.ACTID)),' ') AS "SIGNATAIRE AG",
    NVL (SUBSTR (AG.ACTNOM, 14, 50),' ') as "NOMAGENCE",
      NVL (SUBSTR (AG.ACTNOM, 14, 50),' ')  AS "AGVILLEB",
       TO_CHAR (SYSDATE, 'DD/MM/YYYY') AS "DATEJOUR",
       (SELECT TO_CHAR (MAX(CREDTVALID), 'DD/MM/YYYY')
          FROM CREVT CRE   WHERE CRE.TMFFONCTION = 'EVF_VALIDER' AND CRE.DOSIDPROSPECT = DPR.DOSID )  AS "DEMANDEFINB",
       (SELECT MAX (UTI.UTINOM)
          FROM LKACTUTITSM LK, UTILISATEUR UTI
         WHERE     LK.TSMMETIER = 'PORTFL'
               AND LK.ACTID = PA_REQUETE_OUTILS_AV.F_ID_ACTEUR_ROLE (DPR.DOSID,DPR.DPRVERSION,'CLIENT') AND LK.UTICODE = UTI.UTICODE) AS INTERNOMAG,
       (SELECT MAX (UTI.UTIPRENOM)
          FROM LKACTUTITSM LK, UTILISATEUR UTI
         WHERE     LK.TSMMETIER = 'PORTFL'
               AND LK.ACTID =  PA_REQUETE_OUTILS_AV.F_ID_ACTEUR_ROLE (DPR.DOSID,DPR.DPRVERSION,'CLIENT') AND LK.UTICODE = UTI.UTICODE) AS INTERPRENOMAG,
       PAV4_JASPER_FO.F_GET_TEL_CA_FO (ACTE.ACTID)    AS "TELAG",
       PAV4_JASPER_FO.F_GET_EMAIL_CA_FO (ACTE.ACTID)  AS "MAILAG",
       PAV4_JASPER_FO.F_GET_MOB_CA_FO (ACTE.ACTID) AS "MOBAG",
       PAV4_JASPER_FO.F_GET_FAX_CA_FO (ACTE.ACTID)  AS "FAXAG",
       nvl(PAV4_JASPER_FO.F_GET_ENCOURS_ACTEUR_CTRACTIF (ACTE.ACTID),0) AS "Encours CTR ACTIF" ,
       PAV4_JASPER_FO.F_GET_MTINI_CTRACTIF_ACTEUR (ACTE.ACTID) AS "MT_INI_CTR_ACTIF",
       PAV4_JASPER_FO.F_GET_DTENCOURS_ACTEUR_CTRACTIF (ACTE.ACTID ) AS "Date encouts client CTR ACTIF",
	     PAV4_JASPER_FO.F_GET_ENCOURS_ACTEUR_CTRENG (ACTE.ACTID) AS "Encours CTR ENG" ,
       PAV4_JASPER_FO.F_GET_MTINI_CTRACENG_ACTEUR (ACTE.ACTID) AS "MT_INI_CTR_ENG",
       PAV4_JASPER_FO.F_GET_DTENCOURS_ACTEUR_CTRENG (ACTE.ACTID ) AS "Date encouts client CTR ENG",
	     PAV4_JASPER_FO.F_GET_IMPAYE_ACTEUR (ACTE.ACTID , SYSDATE) AS "Impaye_Acteur" ,
       PAV4_JASPER_FO.F_GET_DT_IMPAYE_ACTEUR (ACTE.ACTID , SYSDATE) AS "DT_Impaye_Acteur" ,
	   PAV4_JASPER_FO.F_GET_COUNT_CTR_ECHU (ACTE.ACTID) AS "NB_CTR_ECHU" ,
	   PAV4_JASPER_FO.F_GET_MT_INV_CTR_ECH (ACTE.ACTID) AS "MTINV_CTR_ECHU" ,
     PAV4_JASPER_FO.F_GET_DTENCOURS_ACTEUR_CTRAECHUS (ACTE.ACTID) "Date encouts client CTR ECH",
       
       ACTE.ROLCODE AS "ROLE",
       NVL(PAV4_JASPER_FO.F_GET_LISTE_SIGNATAIRE_ACTEUR (ACTE.ACTID),' ') as "SIGNATAIRE",
       DPR.DPRVERSION AS "DPRVERSION"
  FROM DOSSIERPROSPECT DPR, DPRACTEUR ACTE ,acteur act ,ADRESSE ADR, ACTADRESSE AAD, CODEPOSTAL COP ,LANPAYS LP, LANCATJURIDIQUE LCJ,ADRESSE ADR1, ACTADRESSE AAD1,
  CODEPOSTAL COP1,LANNAF NAF ,DPRACTEUR DPAG,ACTEUR AG
 WHERE     ACTE.DOSID(+) = DPR.DOSID
       AND ACTE.DPRVERSION(+) = DPR.DPRVERSION
       AND Dpr.Dprversion = F_DERNIEREVERSIONDOSSIER (DPR.DOSID)
       AND acte.actid=act.actid
       AND act.actid=aad.actid(+) AND AAD.AADFLAGSIEGE(+)= 1 AND ADR.ADRID(+) = AAD.ADRID AND AAD.AADDTREMPLACE (+) IS NULL
       AND ADR.ADRCODEPOST = COP.CPOCODE(+) AND ADR.paycode = COP.paycode(+) AND ADR.ADRVILLE = COP.CPOVILLE(+)
      AND (AAD.AADORDRE=(SELECT Max(A.AADORDRE) FROM ACTADRESSE A WHERE A.ACTID=AAD.ACTID AND A.AADFLAGSIEGE=1 AND A.AADDTREMPLACE IS NULL) OR AAD.AADORDRE IS NULL)
      AND COP.PAYCODE=LP.PAYCODE(+) AND LP.LANCODE(+)='FR'
       AND act.actid=aad1.actid(+) AND AAD1.AADFLAGLIVRAISON(+)= 1 AND ADR1.ADRID(+) = AAD1.ADRID AND AAD.AADDTREMPLACE (+) IS NULL
       AND ADR1.ADRCODEPOST = COP1.CPOCODE(+) AND ADR1.paycode = COP1.paycode(+) AND ADR1.ADRVILLE = COP1.CPOVILLE(+)
      AND (AAD1.AADORDRE=(SELECT Max(A.AADORDRE) FROM ACTADRESSE A WHERE A.ACTID=AAD1.ACTID AND A.AADFLAGLIVRAISON=1 AND A.AADDTREMPLACE IS NULL) OR AAD1.AADORDRE IS NULL)
      AND LCJ.CJUCODE(+)=ACT.CJUCODE AND LCJ.LANCODE(+)='FR'  AND LCJ.PAYCODE(+)=ACT.PAYCODE
      AND naf.nafcode(+)=act.nafcode AND naf.lancode(+)='FR'  AND naf.PAYCODE(+)=act.PAYCODE
      AND DPAG.DOSID(+)=DPR.DOSID AND DPAG.DPRVERSION(+)=DPR.DPRVERSION AND DPAG.ROLCODE(+)='AGENCE' AND DPAG.ACTID=AG.ACTID(+);
