
------changement study file pour RMCP lors de saisie de decison 


Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2086',null,null,'ATDECI',null,null,null,'RMCP',null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);




Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2086','dealDetail.dealDetailBodySid.tabPane.secStudy','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2086','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','0','0',null);


commit ;