---U_CLEXT


--------LKTTCTEV

Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE)

values ('CBI','AVDOSS','U_DPR','AVDOSS','U_CLEXT','AVDOSS','EVF_VALIDER','CBI01','1',null,'1',null,null,null);

Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE)

values ('CBM','AVDOSS','U_DPR','AVDOSS','U_CLEXT','AVDOSS','EVF_VALIDER','AUT','1',null,'1',null,null,null);

Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE)

values ('CBM','AVDOSS','U_DPR','AVDOSS','U_CLEXT','AVDOSS','EVF_VALIDER','AUT02','1',null,'1',null,null,null);

Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE)

values ('CBM','AVDOSS','U_DPR','AVDOSS','U_CLEXT','AVDOSS','EVF_VALIDER','CBM01','1',null,'1',null,null,null);

Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE)

values ('GLOBAL','AVDOSS','U_DPR','AVDOSS','U_CLEXT','AVDOSS','EVF_VALIDER','TOUT','1',null,'1',null,null,null);

commit ;


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE)

values ('10','dealDetail.dealDetailBodySid.tabPane.secDealActeur.pngIdentify.pnlIdentify.tfdActcodeclient','0','1','0','0',null);


commit ;


-------------------------------------

--- LANTPCTACCONTROLE



Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) values ('U_DPR','AVDOSS','GLOBAL','U_CLEXT','FR','Le Client doit etre rattaché',null);
Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) values ('U_DPR','AVDOSS','CBM','U_CLEXT','FR','Le Client doit etre rattaché',null);
Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) values ('U_DPR','AVDOSS','CBI','U_CLEXT','FR','Le Client doit etre rattaché',null);
Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) values ('U_DPR','AVDOSS','EMPRUNT','U_CLEXT','FR','Le Client doit etre rattaché',null);



------ WSTCONSEQUENCE



Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST)
values ('WFCLIPRO','2','10','CONTROLS','U_CLEXT',null,null,null);



Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST)
values ('WFCLIPRO','5','2','CONTROLS','U_CLEXT',null,null,null);



Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST)
values ('WFCLICOM','1','2','CONTROLS','U_CLEXT',null,null,null);


Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST)
values ('WFCLICOM','14','12','CONTROLS','U_CLEXT',null,null,null);

----LANWSTCONSEQUENCE



Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION)
values ('WFCLIPRO','2','10','FR',null,null);



Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION)
values ('WFCLIPRO','5','2','FR',null,null);



Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION)
values ('WFCLICOM','1','2','FR',null,null);



Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION)
values ('WFCLICOM','14','12','FR',null,null);



commit ;

