
-----CONFIGURATIONKEY


--Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
--values ('2017',null,null,'D_CREE',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

--Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
--values ('2018',null,null,'CONSSGL',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

--Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
--values ('2024',null,null,'DVCLT',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

--Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
--values ('2012',null,null,'DACPT',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

--Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
--values ('2023',null,null,'DVCOM',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

--Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
--values ('2025',null,null,'ATDECI',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);



Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2066',null,null,'DECDCI',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2067',null,null,'CONSSC',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2068',null,null,'CONSSG',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2069',null,null,'WPROD',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2070',null,null,'TRAKO',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);


Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2071',null,null,'TRANSOK',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2072',null,null,'DTBO',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2073',null,null,'DAJRN',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2074',null,null,'DVAC',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2075',null,null,'DADG',null,null,null,null,null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

commit ;

----------CLIENT

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2017','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2018','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2024','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2066','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2012','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2069','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2070','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2071','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2072','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2073','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2074','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2022','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2075','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);
---------donnee generale 

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2017','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2018','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2024','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2066','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2012','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2069','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2070','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2071','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2072','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2073','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2074','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2022','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2075','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);
-----------------asset

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2017','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2018','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2024','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2066','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2012','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2069','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2070','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2071','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2072','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2073','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2074','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2022','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);
Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2075','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

----------------quote


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2017','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2018','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2024','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2066','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2012','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2069','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2070','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2071','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2072','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2073','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2074','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);
Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2022','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2075','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);
---------Decesion

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2017','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2018','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2024','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2066','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2012','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2069','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2070','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2071','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2072','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2073','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2074','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2022','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2075','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

-------checklist
Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2017','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2018','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2024','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2066','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2012','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2069','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2070','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2071','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2072','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2073','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2074','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2022','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2075','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

-------study file


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2017','dealDetail.dealDetailBodySid.tabPane.secStudy','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2018','dealDetail.dealDetailBodySid.tabPane.secStudy','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2024','dealDetail.dealDetailBodySid.tabPane.secStudy','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2066','dealDetail.dealDetailBodySid.tabPane.secStudy','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2012','dealDetail.dealDetailBodySid.tabPane.secStudy','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2069','dealDetail.dealDetailBodySid.tabPane.secStudy','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2070','dealDetail.dealDetailBodySid.tabPane.secStudy','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2071','dealDetail.dealDetailBodySid.tabPane.secStudy','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2072','dealDetail.dealDetailBodySid.tabPane.secStudy','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2073','dealDetail.dealDetailBodySid.tabPane.secStudy','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2074','dealDetail.dealDetailBodySid.tabPane.secStudy','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2022','dealDetail.dealDetailBodySid.tabPane.secStudy','0','0','1','0',null);


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2075','dealDetail.dealDetailBodySid.tabPane.secStudy','0','0','1','0',null);

-------checklist
Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2017','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2018','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2024','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2066','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2012','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2069','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2070','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2071','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2072','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2073','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2074','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2022','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2075','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);
-------ACteurs

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2017','dealDetail.dealDetailBodySid.tabPane.secDealActeurs','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2018','dealDetail.dealDetailBodySid.tabPane.secDealActeurs','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2024','dealDetail.dealDetailBodySid.tabPane.secDealActeurs','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2066','dealDetail.dealDetailBodySid.tabPane.secDealActeurs','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2012','dealDetail.dealDetailBodySid.tabPane.secDealActeurs','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2069','dealDetail.dealDetailBodySid.tabPane.secDealActeurs','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2070','dealDetail.dealDetailBodySid.tabPane.secDealActeurs','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2071','dealDetail.dealDetailBodySid.tabPane.secDealActeurs','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2072','dealDetail.dealDetailBodySid.tabPane.secDealActeurs','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2073','dealDetail.dealDetailBodySid.tabPane.secDealActeurs','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2074','dealDetail.dealDetailBodySid.tabPane.secDealActeurs','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2022','dealDetail.dealDetailBodySid.tabPane.secDealActeurs','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2075','dealDetail.dealDetailBodySid.tabPane.secDealActeurs','0','0','1','0',null);

---Intervenants
Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2017','dealDetail.dealDetailBodySid.tabPane.secInvolvedUsers','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2018','dealDetail.dealDetailBodySid.tabPane.secInvolvedUsers','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2024','dealDetail.dealDetailBodySid.tabPane.secInvolvedUsers','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2066','dealDetail.dealDetailBodySid.tabPane.secInvolvedUsers','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2012','dealDetail.dealDetailBodySid.tabPane.secInvolvedUsers','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2069','dealDetail.dealDetailBodySid.tabPane.secInvolvedUsers','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2070','dealDetail.dealDetailBodySid.tabPane.secInvolvedUsers','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2071','dealDetail.dealDetailBodySid.tabPane.secInvolvedUsers','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2072','dealDetail.dealDetailBodySid.tabPane.secInvolvedUsers','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2073','dealDetail.dealDetailBodySid.tabPane.secInvolvedUsers','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2074','dealDetail.dealDetailBodySid.tabPane.secInvolvedUsers','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2022','dealDetail.dealDetailBodySid.tabPane.secInvolvedUsers','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2075','dealDetail.dealDetailBodySid.tabPane.secInvolvedUsers','0','0','1','0',null);


---Schema deci
Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2017','dealDetail.dealDetailBodySid.tabPane.secSchemaDeci','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2018','dealDetail.dealDetailBodySid.tabPane.secSchemaDeci','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2024','dealDetail.dealDetailBodySid.tabPane.secSchemaDeci','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2066','dealDetail.dealDetailBodySid.tabPane.secSchemaDeci','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2012','dealDetail.dealDetailBodySid.tabPane.secSchemaDeci','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2069','dealDetail.dealDetailBodySid.tabPane.secSchemaDeci','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2070','dealDetail.dealDetailBodySid.tabPane.secSchemaDeci','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2071','dealDetail.dealDetailBodySid.tabPane.secSchemaDeci','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2072','dealDetail.dealDetailBodySid.tabPane.secSchemaDeci','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2073','dealDetail.dealDetailBodySid.tabPane.secSchemaDeci','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2074','dealDetail.dealDetailBodySid.tabPane.secSchemaDeci','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2022','dealDetail.dealDetailBodySid.tabPane.secSchemaDeci','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2075','dealDetail.dealDetailBodySid.tabPane.secSchemaDeci','0','0','1','0',null);
----historiques  

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2017','dealDetail.dealDetailBodySid.tabPane.secPastEvent','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2018','dealDetail.dealDetailBodySid.tabPane.secPastEvent','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2024','dealDetail.dealDetailBodySid.tabPane.secPastEvent','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2066','dealDetail.dealDetailBodySid.tabPane.secPastEvent','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2012','dealDetail.dealDetailBodySid.tabPane.secPastEvent','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2069','dealDetail.dealDetailBodySid.tabPane.secPastEvent','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2070','dealDetail.dealDetailBodySid.tabPane.secPastEvent','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2071','dealDetail.dealDetailBodySid.tabPane.secPastEvent','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2072','dealDetail.dealDetailBodySid.tabPane.secPastEvent','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2073','dealDetail.dealDetailBodySid.tabPane.secPastEvent','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2074','dealDetail.dealDetailBodySid.tabPane.secPastEvent','0','0','1','0',null);


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2022','dealDetail.dealDetailBodySid.tabPane.secPastEvent','0','0','1','0',null);


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2075','dealDetail.dealDetailBodySid.tabPane.secPastEvent','0','0','1','0',null);

commit ; 


