

----EXTSGMAFOT-89

delete from lkancanl  where ratid =    10002  ;

commit ;

update LKCKEGRE set EGRFLAGDISABLED=1 where ckeid=2012 and GRECODE='dealDetail.dealDetailBodySid.tabPane.secStudy';
commit;

--- TPCTACCONTROLE
Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','CBM','U_COM3','3162','SGM',null,null);
Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','CBI','U_COM3','3162','SGM',null,null);


-- LANTPCTACCONTROLE

Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) values ('U_DPR','AVDOSS','CBM','U_COM3','FR','controle Checklist de transfert CLICOM',null);
Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) values ('U_DPR','AVDOSS','CBI','U_COM3','FR','controle Checklist de transfert CLICOM',null);


-------WSTCONSEQUENCE
Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST) 
values ('WFCLIPRO','10','4','CONTROLS','U_COM3',null,null,null);

----LANWSTCONSEQUENCE

Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION)
 values ('WFCLIPRO','10','4','FR','Control',null);
 
 
 
----- LKTTCTEV

Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE) values ('CBI','AVDOSS','U_DPR','AVDOSS','U_COM3','AVDOSS','EVF_TRANSFERT','CBI01','1',null,'1',null,null,null);
Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE) values ('CBM','AVDOSS','U_DPR','AVDOSS','U_COM3','AVDOSS','EVF_TRANSFERT','AUT','1',null,'1',null,null,null);
Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE) values ('CBM','AVDOSS','U_DPR','AVDOSS','U_COM3','AVDOSS','EVF_TRANSFERT','AUT02','1',null,'1',null,null,null);
Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE) values ('CBM','AVDOSS','U_DPR','AVDOSS','U_COM3','AVDOSS','EVF_TRANSFERT','CBM01','1',null,'1',null,null,null);
Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE) values ('GLOBAL','AVDOSS','U_DPR','AVDOSS','U_COM3','AVDOSS','EVF_TRANSFERT','TOUT','1',null,'1',null,null,null);


commit ;