--------EXTSGMAFOT-63
-----retour pour completure  chez RISQ si ajournement ---CLICOM

-----LANWORSTEP

Insert into LANWORSTEP (WORCODE,WSTORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLICOM','21','FR','Retour pour complétude' ,'Retour pour complétude apres Tirage');


----- WORSTEP

Insert into WORSTEP (WORCODE,WSTORDER,WSTEXECUTIONORDER,WSTTYPE,WSTACTIONTYPE,WSTACTIONCODE,WSTACTIONMODE,WSTFLAGEXECUTEONCE,WSTEXECUTIONMODE,RULIDJUMPAUTO) 
values ('WFCLICOM','21','21',null,'EVT','EVF_VALIDER',null,'0','AUTO',null);


update wstjump  set wstorderdest='21'  where worcode='WFCLICOM'  and wstorder =18  and WORCODEDEST ='WFCLICOM' and wstorderdest =11 and rulid =1000   ;  


-----WSTCONSEQUENCE

Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST) 
values ('WFCLICOM','21','1','CHANGE_PHASE','DAJRN',null,null,null);
Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST) 
values ('WFCLICOM','21','2','FORMALITE',50035,null,null,null);

-----LANWSTCONSEQUENCE

Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLICOM','21','1','FR','Status',null);
Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLICOM','21','2','FR','Notification',null);




---- CUSDEFDATA

Insert into CUSDEFDATA (CSEID,CDEORDRE,CDDORDRE,CDDSTRINGVALUE,CDDNUMERICVALUE,CDDDATEVALUE,CDDBOOLEANVALUE) values ('19','1','2021',null,'21',null,null);
Insert into CUSDEFDATA (CSEID,CDEORDRE,CDDORDRE,CDDSTRINGVALUE,CDDNUMERICVALUE,CDDDATEVALUE,CDDBOOLEANVALUE) values ('19','2','2021','WFCLICOM',null,null,null);

----- CDDRUL

Insert into CDDRUL (CSEID,CDEORDRE,CDDORDRE,RULID) values ('19','1','2021','513');
Insert into CDDRUL (CSEID,CDEORDRE,CDDORDRE,RULID) values ('19','2','2021','513');

---------retour apres completude chez le charge d etude

-----LANWORSTEP

Insert into LANWORSTEP (WORCODE,WSTORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLICOM','22','FR','Retour apres complétude' ,'Retour apres complétude apres Tirage');


----- WORSTEP

Insert into WORSTEP (WORCODE,WSTORDER,WSTEXECUTIONORDER,WSTTYPE,WSTACTIONTYPE,WSTACTIONCODE,WSTACTIONMODE,WSTFLAGEXECUTEONCE,WSTEXECUTIONMODE,RULIDJUMPAUTO) 
values ('WFCLICOM','22','22',null,'EVT','EVF_VALIDER',null,'0','AUTO',null);



-----WSTCONSEQUENCE

Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST) 
values ('WFCLICOM','22','1','CHANGE_PHASE','DVAC',null,null,null);
Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST) 
values ('WFCLICOM','22','2','FORMALITE',30544,null,null,null);

-----LANWSTCONSEQUENCE

Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLICOM','22','1','FR','Status',null);
Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLICOM','22','2','FR','Notification',null);


---- CUSDEFDATA

Insert into CUSDEFDATA (CSEID,CDEORDRE,CDDORDRE,CDDSTRINGVALUE,CDDNUMERICVALUE,CDDDATEVALUE,CDDBOOLEANVALUE) values ('19','1','2022',null,'22',null,null);
Insert into CUSDEFDATA (CSEID,CDEORDRE,CDDORDRE,CDDSTRINGVALUE,CDDNUMERICVALUE,CDDDATEVALUE,CDDBOOLEANVALUE) values ('19','2','2022','WFCLICOM',null,null,null);

----- CDDRUL

Insert into CDDRUL (CSEID,CDEORDRE,CDDORDRE,RULID) values ('19','1','2022','508');
Insert into CDDRUL (CSEID,CDEORDRE,CDDORDRE,RULID) values ('19','2','2022','508');

----WSTJUMP

Insert into WSTJUMP (WORCODE,WSTORDER,WORCODEDEST,WSTORDERDEST,RULID) values ('WFCLICOM','21','WFCLICOM','22',null);
Insert into WSTJUMP (WORCODE,WSTORDER,WORCODEDEST,WSTORDERDEST,RULID) values ('WFCLICOM','22','WFCLICOM','18',null);

commit ;




