--------EXTSGMAFOT-63
-----retour pour completure  chez RISQ si ajournement 

-----LANWORSTEP

Insert into LANWORSTEP (WORCODE,WSTORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLIPRO','26','FR','Retour pour complitude' ,'Retour pour complitude apres Tirage');


----- WORSTEP

Insert into WORSTEP (WORCODE,WSTORDER,WSTEXECUTIONORDER,WSTTYPE,WSTACTIONTYPE,WSTACTIONCODE,WSTACTIONMODE,WSTFLAGEXECUTEONCE,WSTEXECUTIONMODE,RULIDJUMPAUTO) 
values ('WFCLIPRO','26','26',null,'EVT','EVF_VALIDER',null,'0','AUTO',null);


update wstjump  set wstorderdest='26'  where worcode='WFCLIPRO'  and wstorder =22  and WORCODEDEST ='WFCLIPRO' and wstorderdest =23 and rulid =1000   ;  


---- FORMALITE

Insert into FORMALITE (FORID,FORCODE,FORDEST,TACCODE,UGECODE,DOCIDEMIS,FORIDRAPPEL,FORDELAIEMIS,FORFLAGDOCEMIS,FORFLAGREPONSE,FORDELAIREP,FORFLAGFORRAPPEL,FORFLAGOBLIG,FORTYPEDATE,FORMODELANCEMENT,FORFLAGRECURRENT,FORPERIODE,FORMULTIPLE,FORJOUR,FORMOIS,FORDELAIREACTIVATION,FORDELAIREPONSEHEURE,FORNBACREER,FORTYPEJOUR,FORTYPERECURRENCE,FORPRIORITY,FORTYPE,FORPEREMIS,FORPERACT,FORPERREP,FORPERREPONSE,FORTYPEMSG,ANMID,FORTELTYPE,FORPROCEDURE,FORGROUP,CALID,FORGAPTYPE,TGRID,FORCLOSING,FORSTEPCODESOURCE,FORSTEPCODETARGET,FORFLAGREMINDER,FORREMMETHOD,FORREMPERIODBEFORE,FORREMMULTIPLEBEFORE,FORREMPERIODAFTER,FORREMMULTIPLEAFTER,FORPROCRUN,FORDTFREQUENCYTIME,FORWEIGHT,RMAID,SLAID,FORMESSAGE,FORTARGETTYPE,FOREXTERNALADDRESS,DMATYPE) 
values ('50035','50035','AVDOSS','GLOBAL','SGM',null,null,'0','0','2','1','0','0','DTIMME','EVT','0','J','0','0',null,'0',null,null,null,null,null,'GESTADM',null,null,null,null,null,null,null,null,null,'5','OUVRE',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

--- LANFORMALITE

Insert into LANFORMALITE (FORID,LANCODE,FORLIBELLE,FORDESCRIPTION) values ('50035','FR','Retour pour complétude',null);

----FORDESTINATION

Insert into FORDESTINATION (FORID,TPGCODE,FDEORDRE,FDEULYSENDER,FDEUTICODESENDER,FDEGROCODESENDER,FDESECTGESTIONSENDER,FDEMETIERSENDER,FDEULYRECEIVER,FDEUTICODERECEIVER,FDEGROCODERECEIVER,FDESECTGESTIONRECEIVER,FDEMETIERRECEIVER,FDEACTION,FDEPRIORITY,FDEWORCODE,FDEWSTORDER,FDEWEIGHT,TCUCODE) 
values ('50035','TOUT','1',null,null,null,null,null,'GRORECEIVE',null,'CASGL','SGMLEA',null,null,null,null,null,null,null);


-----WSTCONSEQUENCE

Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST) 
values ('WFCLIPRO','26','1','CHANGE_PHASE','DAJRN',null,null,null);
Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST) 
values ('WFCLIPRO','26','2','FORMALITE',(select forid from formalite where forcode='50035' ),null,null,null);

-----LANWSTCONSEQUENCE

Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLIPRO','26','1','FR','Status',null);
Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLIPRO','26','2','FR','Notification',null);




---- CUSDEFDATA

Insert into CUSDEFDATA (CSEID,CDEORDRE,CDDORDRE,CDDSTRINGVALUE,CDDNUMERICVALUE,CDDDATEVALUE,CDDBOOLEANVALUE) values ('19','1','1026',null,'26',null,null);
Insert into CUSDEFDATA (CSEID,CDEORDRE,CDDORDRE,CDDSTRINGVALUE,CDDNUMERICVALUE,CDDDATEVALUE,CDDBOOLEANVALUE) values ('19','2','1026','WFCLIPRO',null,null,null);

----- CDDRUL

Insert into CDDRUL (CSEID,CDEORDRE,CDDORDRE,RULID) values ('19','1','1026','513');
Insert into CDDRUL (CSEID,CDEORDRE,CDDORDRE,RULID) values ('19','2','1026','513');

---------retour apres completude chez le charge d etude

----LANRULE

Insert into LANRULE (RULID,LANCODE,RULLABEL) values ('521','EN','Charges d etude Sogelease');
Insert into LANRULE (RULID,LANCODE,RULLABEL) values ('521','FR','Charges d etude Sogelease');

----WSTJUMP

Insert into WSTJUMP (WORCODE,WSTORDER,WORCODEDEST,WSTORDERDEST,RULID) values ('WFCLIPRO','26','WFCLIPRO','23',null);

commit ;




