
-------------EXTSGMAFOT-137

-------TPCTACCONTROLE

Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','GLOBAL','U_CLTPR','3162','SGM',null,null);
Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','CBM','U_CLTPR','3162','SGM',null,null);
Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','CBI','U_CLTPR','3162','SGM',null,null);
Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','EMPRUNT','U_CLTPR','3162','SGM',null,null);



---------LANTPCTACCONTROLE

Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) 
values ('U_DPR','AVDOSS','CBI','U_CLTPR','FR','Un seul client preneur doit rattaché à la demande',null);
Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO)
 values ('U_DPR','AVDOSS','EMPRUNT','U_CLTPR','FR','Un seul client preneur doit rattaché à la demande',null);
Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) 
values ('U_DPR','AVDOSS','GLOBAL','U_CLTPR','FR','Un seul client preneur doit rattaché à la demande',null);
Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) 
values ('U_DPR','AVDOSS','CBM','U_CLTPR','FR','Un seul client preneur doit rattaché à la demande',null);

------LKPHATTC


Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) values ('U_DPR','AVDOSS','CBM','U_CLTPR','NEGO','AVDOSS','CBM01','1','0','1',null);
Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) values ('U_DPR','AVDOSS','CBM','U_CLTPR','NEGO','AVDOSS','AUT','1','0','1',null);
Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) values ('U_DPR','AVDOSS','CBI','U_CLTPR','NEGO','AVDOSS','CBI01','1','0','1',null);
Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) values ('U_DPR','AVDOSS','CBM','U_CLTPR','NEGO','AVDOSS','AUT02','1','0','1',null);
Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) values ('U_DPR','AVDOSS','GLOBAL','U_CLTPR','NEGO','AVDOSS','TOUT','1','0','1',null);

Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) values ('U_DPR','AVDOSS','CBM','U_CLTPR','FIN','AVDOSS','CBM01','1','0','1',null);
Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) values ('U_DPR','AVDOSS','CBM','U_CLTPR','FIN','AVDOSS','AUT','1','0','1',null);
Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) values ('U_DPR','AVDOSS','CBI','U_CLTPR','FIN','AVDOSS','CBI01','1','0','1',null);
Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) values ('U_DPR','AVDOSS','CBM','U_CLTPR','FIN','AVDOSS','AUT02','1','0','1',null);
Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) values ('U_DPR','AVDOSS','GLOBAL','U_CLTPR','FIN','AVDOSS','TOUT','1','0','1',null);




commit ;