 
 -----EXTSGMAFOT-121

-----TPCTACCONTROLE

Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','GLOBAL','U_DAUT','3162','SGM',null,null);
Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','CBM','U_DAUT','3162','SGM',null,null);

---- LANTPCTACCONTROLE

Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO)
 values ('U_DPR','AVDOSS','GLOBAL','U_DAUT','FR','Les champs date facture proforma,num facture et Fournisseur doivent etre renseignés',null);

Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) 
values ('U_DPR','AVDOSS','CBM','U_DAUT','FR','Les champs date facture proforma,num facture et Fournisseur doivent etre renseignés',null);


---- LKTTCTEV 
 
 Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE)
 values ('CBM','AVDOSS','U_DPR','AVDOSS','U_DAUT','AVDOSS','EVF_TIRAGE','AUT','1',null,'1',null,null,null);
 
 
 Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE)
 values ('CBM','AVDOSS','U_DPR','AVDOSS','U_DAUT','AVDOSS','EVF_TIRAGE','AUT02','1',null,'1',null,null,null);
 

Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE)
 values ('GLOBAL','AVDOSS','U_DPR','AVDOSS','U_DAUT','AVDOSS','EVF_TIRAGE','TOUT','1',null,'1',null,null,null);


---- WSTCONSEQUENCE
Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST)
 values ('WFCLIPRO','21','6','CONTROLS','U_DAUT',null,null,null);

Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLIPRO','21','9','FR',null,null);


Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST)
 values ('WFCLICOM','12','7','CONTROLS','U_DAUT',null,null,null);

Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLICOM','12','7','FR',null,null);


 
	commit ;