
 -----EXTSGMAFOT-118


      delete from  RELATIONVALEURPROFIL   where RECCODE     ='INTERVDOSRESEAU'     and REVFILLECODE  
           not in ('DSGLM') and REVMERECODE   = 'MEHDIM'   ;
		   
	

      
            update RELATIONVALEURPROFIL    set REVFILLECODE = 'DSGLM' , revflagdefaut=1  
            WHERE RECCODE     ='INTERVDOSRESEAU'
            AND REVMERECODE   = 'AMINEB'   and tpgcode in ( 'AUT' ,'CBM01', 'CBI01','AUT02');
  
   Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('INTERVDOSRESEAU','CBM01','AMINEB','DSGLM','1');
   Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('INTERVDOSRESEAU','CBI01','AMINEB','DSGLM','1');          

-- RELATIONVALEURPROFIL

Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('INTERVDOSRESEAU','CBM01','MOHAMEDEA','DSGLM','1');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('INTERVDOSRESEAU','CBI01','MOHAMEDEA','DSGLM','1');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('INTERVDOSRESEAU','AUT','MOHAMEDEA','DSGLM','1');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('INTERVDOSRESEAU','AUT02','MOHAMEDEA','DSGLM','1');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('INTERVDOSRESEAU','TOUT','MOHAMEDEA','DSGLM',null);

            


	
		   commit ;