  


---EXTSGMAFOT-76

-------- TPCTACCONTROLE

Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) 
values ('U_U02','ACTEUR','GLOBAL','U_DCREA','3162','SGM',null,null);



-------LANTPCTACCONTROLE

Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) 
values ('U_U02','ACTEUR','GLOBAL','U_DCREA','FR','La date de creation ne peut pas etre superieure à la sysdtae',null);




-----LKPHATTC

Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE)
 values ('U_U02','ACTEUR','GLOBAL','U_DCREA','ACTIVE','ACTEUR','TOUT',null,null,'1',null);
 
Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) 
values ('U_U02','ACTEUR','GLOBAL','U_DCREA','INI','ACTEUR','TOUT','0',null,'1',null);

Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) 
values ('U_U02','ACTEUR','GLOBAL','U_DCREA','TER','ACTEUR','TOUT','0',null,'1',null);


Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) 
values ('U_U02','ACTEUR','GLOBAL','U_DCREA','PRECTX','ACTEUR','TOUT','0',null,'1',null);

Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) 
values ('U_U02','ACTEUR','GLOBAL','U_DCREA','CTX','ACTEUR','TOUT','0',null,'1',null);



commit ;
