------EXTSGMAFOT-36

---- TPCTACCONTROLE

Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','GLOBAL','U_EXTCA','3162','SGM',null,null);
Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','CBM','U_EXTCA','3162','SGM',null,null);
Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','CBI','U_EXTCA','3162','SGM',null,null);
Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','EMPRUNT','U_EXTCA','3162','SGM',null,null);


 -----LANTPCTACCONTROLE

Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) 
values ('U_DPR','AVDOSS','CBI','U_EXTCA','FR','Veuillez vérifier la cohérence des éléments financiers saisis avant de passer à l''étape suivante',null);
Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) 
values ('U_DPR','AVDOSS','EMPRUNT','U_EXTCA','FR','Veuillez vérifier la cohérence des éléments financiers saisis avant de passer à l''étape suivante',null);
Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) 
values ('U_DPR','AVDOSS','GLOBAL','U_EXTCA','FR','Veuillez vérifier la cohérence des éléments financiers saisis avant de passer à l''étape suivante',null);
Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) 
values ('U_DPR','AVDOSS','CBM','U_EXTCA','FR','Veuillez vérifier la cohérence des éléments financiers saisis avant de passer à l''étape suivante',null);

--- LKPHATTC

Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) 
values ('U_DPR','AVDOSS','CBM','U_EXTCA','NEGO','AVDOSS','CBM01','1','0','2',null);
Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE)
 values ('U_DPR','AVDOSS','CBM','U_EXTCA','PROD','AVDOSS','CBM01','1','0','2',null);
Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) 
values ('U_DPR','AVDOSS','CBI','U_EXTCA','NEGO','AVDOSS','CBI01','1','0','2',null);
Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) 
values ('U_DPR','AVDOSS','CBI','U_EXTCA','PROD','AVDOSS','CBI01','1','0','2',null);
Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) 
values ('U_DPR','AVDOSS','GLOBAL','U_EXTCA','NEGO','AVDOSS','TOUT','1','0','2',null);
Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) 
values ('U_DPR','AVDOSS','GLOBAL','U_EXTCA','PROD','AVDOSS','TOUT','1','0','2',null);

commit ; 
					  
		