
--EXTSGMAFOT-33
-----CONFIGURATIONKEY

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2045',null,null,'D_CREE',null,null,null,'VENDOR',null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2046',null,null,'CONSCRV',null,null,null,'VENDOR',null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2047',null,null,'DVCLT',null,null,null,'VENDOR',null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2048',null,null,'DECDCI',null,null,null,'VENDOR',null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2049',null,null,'DACPT',null,null,null,'VENDOR',null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2050',null,null,'WPROD',null,null,null,'VENDOR',null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2051',null,null,'TRANSOK',null,null,null,'VENDOR',null,null,'H',null,'NOCRIT','9999999999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

UPDATE  CONFIGURATIONKEY   set  CKEWEIGHT ='99999999' where ckeid =2045 ;
UPDATE  CONFIGURATIONKEY   set  CKEWEIGHT ='99999999999' where ckeid =2045 ;
UPDATE  CONFIGURATIONKEY   set  CKEWEIGHT ='99999999999' where ckeid BETWEEN 2046 AND 2051 ;



Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2045','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2046','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2046','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2046','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2046','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2046','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2046','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  



Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2047','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2047','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2047','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2047','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2047','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2047','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2048','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2048','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2048','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2048','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2048','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2048','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2049','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2049','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2049','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2049','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2049','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2049','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2050','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2050','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2050','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2050','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2050','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2050','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2051','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2051','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2051','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2051','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2051','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2051','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  



commit ; 