
--------EXTSGMAFOT-259

--------LKTTCTEV

Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE) 
values ('CBI','AVDOSS','U_DPR','AVDOSS','U_CLEXT','AVDOSS','EVF_VALIDER','CBI01','1',null,'1',null,null,null);
Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE) 
values ('CBM','AVDOSS','U_DPR','AVDOSS','U_CLEXT','AVDOSS','EVF_VALIDER','AUT','1',null,'1',null,null,null);
Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE) 
values ('CBM','AVDOSS','U_DPR','AVDOSS','U_CLEXT','AVDOSS','EVF_VALIDER','AUT02','1',null,'1',null,null,null);
Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE) 
values ('CBM','AVDOSS','U_DPR','AVDOSS','U_CLEXT','AVDOSS','EVF_VALIDER','CBM01','1',null,'1',null,null,null);
Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE) 
values ('GLOBAL','AVDOSS','U_DPR','AVDOSS','U_CLEXT','AVDOSS','EVF_VALIDER','TOUT','1',null,'1',null,null,null);

 commit ;