
----TPROFILGESTION_BO

Insert into TPROFILGESTION (TPGCODE,TACCODE,TPGDTDEB,TPGDTFIN,TPGMTMINI,TPGMTMAXI,TPGDUREEANMINI,TPGDUREEMOISMINI,TPGDUREEJOURMINI,TPGDUREEANMAXI,TPGDUREEMOISMAXI,TPGDUREEJOURMAXI,TPGFLAGCONSTRUCTION,TPGFLAGIMMOBILIER,TPGFLAGMOBILIER,TPGFLAGREVOLVER,TPGFLAGFACILITY,TPGTYPE,TPGCODEPARENT) 
values ('AUT','CBM',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'1',null,null);


Insert into LANTPROFILGESTION (TPGCODE,LANCODE,TPGLIBELLE,TPGARGUMENT) values ('AUT','FR','Autorisation non revolving CBM',null);

update LKTPGAGE set TAGFLAGDEFAUT = 1 where tpgcode='AUT02' ;
commit ;