---LAD DSRMCP/RISQ
  
  
  update wstjump  set rulid =1002 where worcode='WFCLIPRO'   and WSTORDER  =12 and rulid = 300762 ;
update wstjump  set rulid =1004 where worcode='WFCLIPRO'   and WSTORDER  =12 and rulid = 300763 ;


----- WORSTEP---evenement de pasage vers DIr risque 

Insert into WORSTEP (WORCODE,WSTORDER,WSTEXECUTIONORDER,WSTTYPE,WSTACTIONTYPE,WSTACTIONCODE,WSTACTIONMODE,WSTFLAGEXECUTEONCE,WSTEXECUTIONMODE,RULIDJUMPAUTO) 
values ('WFCLIPRO','27','27',null,'EVT','EVF_VALIDER',null,'0','AUTO',null);

------- LANWORSTEP

Insert into LANWORSTEP (WORCODE,WSTORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLIPRO','27','FR','Soumission pour Décision',null);

------ WSTJUMP

update wstjump  set WSTORDERDEST =27 where worcode='WFCLIPRO'   and WSTORDER  =12 and WSTORDERDEST =18 rulid = 1002 ;     


Insert into WSTJUMP (WORCODE,WSTORDER,WORCODEDEST,WSTORDERDEST,RULID) values ('WFCLIPRO','27','WFCLIPRO','18',null );


----habilitation pour groupe risque 
---- CUSDEFDATA

Insert into CUSDEFDATA (CSEID,CDEORDRE,CDDORDRE,CDDSTRINGVALUE,CDDNUMERICVALUE,CDDDATEVALUE,CDDBOOLEANVALUE) values ('19','1','1027',null,'27',null,null);
Insert into CUSDEFDATA (CSEID,CDEORDRE,CDDORDRE,CDDSTRINGVALUE,CDDNUMERICVALUE,CDDDATEVALUE,CDDBOOLEANVALUE) values ('19','2','1027','WFCLIPRO',null,null,null);

---- CDDRUL

Insert into CDDRUL (CSEID,CDEORDRE,CDDORDRE,RULID) values ('19','1','1027','513');
Insert into CDDRUL (CSEID,CDEORDRE,CDDORDRE,RULID) values ('19','2','1027','513');


--- FORMALITE

Insert into FORMALITE (FORID,FORCODE,FORDEST,TACCODE,UGECODE,DOCIDEMIS,FORIDRAPPEL,FORDELAIEMIS,FORFLAGDOCEMIS,FORFLAGREPONSE,FORDELAIREP,FORFLAGFORRAPPEL,FORFLAGOBLIG,FORTYPEDATE,FORMODELANCEMENT,FORFLAGRECURRENT,FORPERIODE,FORMULTIPLE,FORJOUR,FORMOIS,FORDELAIREACTIVATION,FORDELAIREPONSEHEURE,FORNBACREER,FORTYPEJOUR,FORTYPERECURRENCE,FORPRIORITY,FORTYPE,FORPEREMIS,FORPERACT,FORPERREP,FORPERREPONSE,FORTYPEMSG,ANMID,FORTELTYPE,FORPROCEDURE,FORGROUP,CALID,FORGAPTYPE,TGRID,FORCLOSING,FORSTEPCODESOURCE,FORSTEPCODETARGET,FORFLAGREMINDER,FORREMMETHOD,FORREMPERIODBEFORE,FORREMMULTIPLEBEFORE,FORREMPERIODAFTER,FORREMMULTIPLEAFTER,FORPROCRUN,FORDTFREQUENCYTIME,FORWEIGHT,RMAID,SLAID,FORMESSAGE,FORTARGETTYPE,FOREXTERNALADDRESS,DMATYPE) 
values ('50040','50040','AVDOSS','GLOBAL','SGM',null,null,'0','0','2','1','0','0','DTIMME','EVT','0','J','0','0',null,'0',null,null,null,null,null,'GESTADM',null,null,null,null,null,null,null,null,null,'5','OUVRE',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

---- LANFORMALITE

Insert into LANFORMALITE (FORID,LANCODE,FORLIBELLE,FORDESCRIPTION) values ('50040','FR','Transfert au Directeur Risque pour validation',null);

---- FORDESTINATION

Insert into FORDESTINATION (FORID,TPGCODE,FDEORDRE,FDEULYSENDER,FDEUTICODESENDER,FDEGROCODESENDER,FDESECTGESTIONSENDER,FDEMETIERSENDER,FDEULYRECEIVER,FDEUTICODERECEIVER,FDEGROCODERECEIVER,FDESECTGESTIONRECEIVER,FDEMETIERRECEIVER,FDEACTION,FDEPRIORITY,FDEWORCODE,FDEWSTORDER,FDEWEIGHT,TCUCODE) 
values ('50040','TOUT','1',null,null,null,null,null,'GRORECEIVE',null,'RISQSGL','SGMLEA',null,null,null,null,null,null,null);

-------- WSTCONSEQUENCE

Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST) 
values ('WFCLIPRO','27','1','FORMALITE','50040',null,null,null);

----LANWSTCONSEQUENCE

Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION)
 values ('WFCLIPRO','27','1','FR','Notification',null);





------ RULE grpe dir risque
Insert into RULE (RULID,RULCODE,RULTARGET,RULOPERATOR,RULLOWERLIMIT,RULUPPERLIMIT,RULSTATUS,CRIIDFIRST,RULIDFIRST,RULIDSECOND,CRIIDSECONDMAX,CRIIDSECONDMIN,RULTYPE,RULFLAGCASSIOPAE,RULGROUP) 
values ('3007130','GRP','AVDOSS','LIKE','RISQSGL',null,'ACTIVE','50',null,null,null,null,'LOGICAL',null,null);

---- LANRULE
Insert into LANRULE (RULID,LANCODE,RULLABEL) values ('3007130','FR','Directeur Risque Sogelease');

update cddrul set rulid = 3007130 where  cddordre=1018  and rulid =513 ;
update cddrul  set rulid = 1005   where cddordre=10127 and rulid =300761 ;
update cddrul  set rulid = 1003   where cddordre=10125 and rulid =300760 ;
update cddrul  set rulid = 1005   where cddordre=10187 and rulid =300761 ;

update rulvalue set RULIDVALUE =1002 where rulid =4012 and RULIDVALUE =300760 ;
update rulvalue set RULIDVALUE =1002 where rulid =4013 and RULIDVALUE =300760 ;
update cddrul  set rulid = 1003   where cddordre=10125 and rulid =300760 ;


select * from cddrul  where cddordre=10126 ;---1001DEM_AJOUR

select * from cddrul  where cddordre=10127 ;---DEM_REF
update cddrul  set rulid = 1005   where cddordre=10127 and rulid =300761 ;
update cddrul  set rulid = 1005   where cddordre=10187 and rulid =300761 ;

update wstjump   set rulid = 1002  where worcode='WFCLIPRO'  and WSTORder=18 and WSTORDERDEST=17 and rulid =300763 ;---1002	DEM_ACC

update wstjump   set rulid =  1004 where worcode='WFCLIPRO'  and WSTORder=18 and WSTORDERDEST=15 and rulid =300763 ;--1004	DEM_REF



update rulvalue set RULIDVALUE =1003 where rulid =4013 and RULIDVALUE =1002 ;
update rulvalue set RULIDVALUE =1003 where rulid =4012 and RULIDVALUE =1002 ;

Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','CBM01','RISQSGL','DECIAJ01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','CBM01','RISQSGL','DECIDFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','CBM01','RISQSGL','DECIFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','CBI01','RISQSGL','DECIAJ01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','CBI01','RISQSGL','DECIDFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','CBI01','RISQSGL','DECIFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','AUT','RISQSGL','DECIAJ01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','AUT','RISQSGL','DECIDFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','AUT','RISQSGL','DECIFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','AUT02','RISQSGL','DECIAJ01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','AUT02','RISQSGL','DECIDFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','AUT02','RISQSGL','DECIFA01','0');

Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','CBM01','MOHAMEDEA','DECIAJ01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','CBM01','MOHAMEDEA','DECIDFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','CBM01','MOHAMEDEA','DECIFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','CBI01','MOHAMEDEA','DECIAJ01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','CBI01','MOHAMEDEA','DECIDFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','CBI01','MOHAMEDEA','DECIFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','AUT','MOHAMEDEA','DECIAJ01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','AUT','MOHAMEDEA','DECIDFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','AUT','MOHAMEDEA','DECIFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','AUT02','MOHAMEDEA','DECIAJ01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','AUT02','MOHAMEDEA','DECIDFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERDECI','AUT02','MOHAMEDEA','DECIFA01','0');

Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERGRPDECI','CBM01','RISQSGL','DECIAJ01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERGRPDECI','CBM01','RISQSGL','DECIDFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERGRPDECI','CBM01','RISQSGL','DECIFA01','0');

Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERGRPDECI','CBI01','RISQSGL','DECIAJ01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERGRPDECI','CBI01','RISQSGL','DECIDFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERGRPDECI','CBI01','RISQSGL','DECIFA01','0')

Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERGRPDECI','AUT','RISQSGL','DECIAJ01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERGRPDECI','AUT','RISQSGL','DECIDFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERGRPDECI','AUT','RISQSGL','DECIFA01','0');

Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERGRPDECI','AUT02','RISQSGL','DECIAJ01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERGRPDECI','AUT02','RISQSGL','DECIDFA01','0');
Insert into RELATIONVALEURPROFIL (RECCODE,TPGCODE,REVMERECODE,REVFILLECODE,REVFLAGDEFAUT) values ('USERGRPDECI','AUT02','RISQSGL','DECIFA01','0');

----habilitation event demande arbitrage--cddordre  1017

update cddrul  set rulid =511 where cseid =19 and cddordre =1017 and rulid =510  

-----------
----- WORSTEP---evenement validation DG

Insert into WORSTEP (WORCODE,WSTORDER,WSTEXECUTIONORDER,WSTTYPE,WSTACTIONTYPE,WSTACTIONCODE,WSTACTIONMODE,WSTFLAGEXECUTEONCE,WSTEXECUTIONMODE,RULIDJUMPAUTO) 
values ('WFCLIPRO','28','28',null,'EVT','EVF_VALIDER',null,'0','AUTO',null);

------- LANWORSTEP

Insert into LANWORSTEP (WORCODE,WSTORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLIPRO','28','FR','Validation DG',null);

------ WSTJUMP

update wstjump  set WSTORDERDEST =28 where worcode='WFCLIPRO'   and WSTORDER  =18 and WSTORDERDEST =17 and rulid =1002 ;     
Insert into WSTJUMP (WORCODE,WSTORDER,WORCODEDEST,WSTORDERDEST,RULID) values ('WFCLIPRO','28','WFCLIPRO','10',null );



----habilitation pour groupe DG 
---- CUSDEFDATA

Insert into CUSDEFDATA (CSEID,CDEORDRE,CDDORDRE,CDDSTRINGVALUE,CDDNUMERICVALUE,CDDDATEVALUE,CDDBOOLEANVALUE) values ('19','1','1028',null,'28',null,null);
Insert into CUSDEFDATA (CSEID,CDEORDRE,CDDORDRE,CDDSTRINGVALUE,CDDNUMERICVALUE,CDDDATEVALUE,CDDBOOLEANVALUE) values ('19','2','1028','WFCLIPRO',null,null,null);

---- CDDRUL

Insert into CDDRUL (CSEID,CDEORDRE,CDDORDRE,RULID) values ('19','1','1028','511');
Insert into CDDRUL (CSEID,CDEORDRE,CDDORDRE,RULID) values ('19','2','1028','511');


--- FORMALITE

Insert into FORMALITE (FORID,FORCODE,FORDEST,TACCODE,UGECODE,DOCIDEMIS,FORIDRAPPEL,FORDELAIEMIS,FORFLAGDOCEMIS,FORFLAGREPONSE,FORDELAIREP,FORFLAGFORRAPPEL,FORFLAGOBLIG,FORTYPEDATE,FORMODELANCEMENT,FORFLAGRECURRENT,FORPERIODE,FORMULTIPLE,FORJOUR,FORMOIS,FORDELAIREACTIVATION,FORDELAIREPONSEHEURE,FORNBACREER,FORTYPEJOUR,FORTYPERECURRENCE,FORPRIORITY,FORTYPE,FORPEREMIS,FORPERACT,FORPERREP,FORPERREPONSE,FORTYPEMSG,ANMID,FORTELTYPE,FORPROCEDURE,FORGROUP,CALID,FORGAPTYPE,TGRID,FORCLOSING,FORSTEPCODESOURCE,FORSTEPCODETARGET,FORFLAGREMINDER,FORREMMETHOD,FORREMPERIODBEFORE,FORREMMULTIPLEBEFORE,FORREMPERIODAFTER,FORREMMULTIPLEAFTER,FORPROCRUN,FORDTFREQUENCYTIME,FORWEIGHT,RMAID,SLAID,FORMESSAGE,FORTARGETTYPE,FOREXTERNALADDRESS,DMATYPE) 
values ('50041','50041','AVDOSS','GLOBAL','SGM',null,null,'0','0','2','1','0','0','DTIMME','EVT','0','J','0','0',null,'0',null,null,null,null,null,'GESTADM',null,null,null,null,null,null,null,null,null,'5','OUVRE',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

---- LANFORMALITE

Insert into LANFORMALITE (FORID,LANCODE,FORLIBELLE,FORDESCRIPTION) values ('50041','FR','Demande validee par DG-transfert au risq pour transfert',null);

---- FORDESTINATION

Insert into FORDESTINATION (FORID,TPGCODE,FDEORDRE,FDEULYSENDER,FDEUTICODESENDER,FDEGROCODESENDER,FDESECTGESTIONSENDER,FDEMETIERSENDER,FDEULYRECEIVER,FDEUTICODERECEIVER,FDEGROCODERECEIVER,FDESECTGESTIONRECEIVER,FDEMETIERRECEIVER,FDEACTION,FDEPRIORITY,FDEWORCODE,FDEWSTORDER,FDEWEIGHT,TCUCODE) 
values ('50041','TOUT','1',null,null,null,null,null,'GRORECEIVE',null,'RISQUE','SGMLEA',null,null,null,null,null,null,null);

-------- WSTCONSEQUENCE

Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST) 
values ('WFCLIPRO','28','1','FORMALITE','50041',null,null,null);

----LANWSTCONSEQUENCE

Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION)
 values ('WFCLIPRO','28','1','FR','Notification',null);

