----EXTSGMAFOT-216
----------metier


INSERT INTO TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) VALUES ('METIER','GESREC','0');
INSERT INTO LANtusparam (TUSNOM, TUPCODE, LANCODE, TUPLIBELLE, TUPHELPTEXT) VALUES ('METIER','GESREC','FR','Gestionnaire de recouvrement','null');


update LANtusparam   SET TUPLIBELLE =  'Chargé Recouvrement'  where tusnom = 'METIER'  and TUPCODE='GESREC';
INSERT INTO FILTREPARAMPROFIL  VALUES ('CBI01','2','METIER','GESREC','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('CBM01','2','METIER','GESREC','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('AUT','2','METIER','GESREC','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('TOUT','2','METIER','GESREC','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('AUT02','2','METIER','GESREC','0');



-------TSECTEURMETIER
Insert into TSECTEURMETIER (TSMSECTGESTION,TSMMETIER) values ('SGMLEA','GESREC');

commit ;