
--EXTSGMAFOT-33
-----CONFIGURATIONKEY

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2051','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2050','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2049','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2048','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  
Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2047','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  
Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2046','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  

commit ;


Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2052',null,null,'D_CREE',null,null,null,'SGEC',null,null,'H',null,'NOCRIT','99999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2053',null,null,'CONSCRV',null,null,null,'SGEC',null,null,'H',null,'NOCRIT','99999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2054',null,null,'DVCLT',null,null,null,'SGEC',null,null,'H',null,'NOCRIT','99999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2055',null,null,'DECDCI',null,null,null,'SGEC',null,null,'H',null,'NOCRIT','99999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2056',null,null,'DACPT',null,null,null,'SGEC',null,null,'H',null,'NOCRIT','99999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2057',null,null,'WPROD',null,null,null,'SGEC',null,null,'H',null,'NOCRIT','99999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2058',null,null,'TRANSOK',null,null,null,'SGEC',null,null,'H',null,'NOCRIT','99999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2059',null,null,'CONSSC',null,null,null,'SGEC',null,null,'H',null,'NOCRIT','99999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2060',null,null,'CONSSG',null,null,null,'SGEC',null,null,'H',null,'NOCRIT','99999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2061',null,null,'CONSSGL',null,null,null,'SGEC',null,null,'H',null,'NOCRIT','99999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2062',null,null,'TRAKO',null,null,null,'SGEC',null,null,'H',null,'NOCRIT','99999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);


Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2063',null,null,'DAJRN',null,null,null,'SGEC',null,null,'H',null,'NOCRIT','99999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into CONFIGURATIONKEY (CKEID,TPGCODE,UGECODE,JALCODE,UTICODE,PHACODE,PHADEST,GROCODE,TACCODE,ACTID,CKETYPE,CKECONTEXT,CKENAME,CKEWEIGHT,TBTCODE,TBNCODE,PAYCODE,NAPCODE,CKEENTTYPE,CKEROLCODEEXTERNE,CKETCTCODE,CKEUSERPOSITION,FORID,CKECCATYPE,CKEDEALTYPE,TGACODE,CKETGATYPE,TWCID,CKEACTTYPE,TPGCODEQUOTE,TCACODE) 
values ('2064',null,null,'DVAC',null,null,null,'SGEC',null,null,'H',null,'NOCRIT','99999999999',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

commit ;
/*update CONFIGURATIONKEY  set CKEWEIGHT ='99999999999'  WHERE CKEID =2059;
update CONFIGURATIONKEY  set CKEWEIGHT ='99999999999'  WHERE CKEID in (2052  ,2059);
update CONFIGURATIONKEY  set jalcode= 'CONSSC' ,GROCODE= 'SGEC'  WHERE CKEID in (2059);

update CONFIGURATIONKEY  set  CKEWEIGHT= 99999999999
 ,GROCODE= 'SGEC',jalcode = null   WHERE CKEID in (2063 ,2064 ) ;--(2060 ,2061 ,2062);
update CONFIGURATIONKEY  set jalcode= 'CONSSG'  WHERE CKEID in (2060);
update CONFIGURATIONKEY  set jalcode= 'CONSSGL'  WHERE CKEID in (2061);

update CONFIGURATIONKEY  set jalcode= 'TRAKO'  WHERE CKEID in (2062);

update CONFIGURATIONKEY  set jalcode= 'DAJRN'  WHERE CKEID in (2063);
update CONFIGURATIONKEY  set jalcode= 'DVAC'  WHERE CKEID in (2064);*/



Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2064','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2064','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2064','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2064','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2064','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2064','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2064','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2063','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2063','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2063','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2063','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2063','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2063','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2063','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2062','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2062','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2062','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2062','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2062','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2062','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2062','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  



Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2061','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2061','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2061','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2061','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2061','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2061','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2061','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  



Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2060','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2060','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2060','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2060','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2060','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2060','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2060','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  




Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2059','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2059','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2059','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2059','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2059','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2059','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2059','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  




Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2052','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2052','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2052','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2052','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2052','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','0','0',null);  

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2052','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','0','0',null); 


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2052','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','0','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2053','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2053','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2053','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2053','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2053','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2053','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2053','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  




Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2054','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2054','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2054','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2054','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2054','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2054','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);
Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2054','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  
  


Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2055','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2055','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2055','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2055','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2055','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2055','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  
Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2055','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  



Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2056','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2056','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2056','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2056','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2056','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2056','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  
Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2056','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  



Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2057','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2057','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2057','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2057','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2057','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2057','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2057','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  



Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2058','dealDetail.dealDetailBodySid.tabPane.secDonneesGenerales','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2058','dealDetail.dealDetailBodySid.tabPane.secDealActeur','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2058','dealDetail.dealDetailBodySid.tabPane.secAssets','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2058','dealDetail.dealDetailBodySid.tabPane.secQuote','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2058','dealDetail.dealDetailBodySid.tabPane.secDecision','0','0','1','0',null);

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2058','dealDetail.dealDetailBodySid.tabPane.secDocumentManagement','0','0','1','0',null);  

Insert into LKCKEGRE (CKEID,GRECODE,EGRFLAGHIDDEN,EGRFLAGMANDATORY,EGRFLAGDISABLED,EGRFLAGCOLLAPSED,EGRMASKCODE) 
values ('2058','dealDetail.dealDetailBodySid.tabPane.secCheckList','0','0','1','0',null);  




commit ; 


