----EXTSGMAFOT-216
----------metier


INSERT INTO TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) VALUES ('METIER','GESREC','0');
INSERT INTO LANtusparam (TUSNOM, TUPCODE, LANCODE, TUPLIBELLE, TUPHELPTEXT) VALUES ('METIER','GESREC','FR','Agent recouvrement','null');
INSERT INTO FILTREPARAMPROFIL  VALUES ('CBI01','2','METIER','GESREC','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('CBM01','2','METIER','GESREC','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('AUT','2','METIER','GESREC','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('TOUT','2','METIER','GESREC','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('AUT02','2','METIER','GESREC','0');

-------TSECTEURMETIER
Insert into TSECTEURMETIER (TSMSECTGESTION,TSMMETIER) values ('SGMLEA','GESREC');


Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE)
values ('COMSGL','SGMLEA','GESREC',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

--
INSERT INTO TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) VALUES ('METIER','DIRCOM','0');
INSERT INTO LANtusparam (TUSNOM, TUPCODE, LANCODE, TUPLIBELLE, TUPHELPTEXT) VALUES ('METIER','GESREC','FR','Dir. Com.','null');
INSERT INTO FILTREPARAMPROFIL  VALUES ('CBI01','2','METIER','DIRCOM','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('CBM01','2','METIER','DIRCOM','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('AUT','2','METIER','DIRCOM','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('TOUT','2','METIER','DIRCOM','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('AUT02','2','METIER','DIRCOM','0');

-------TSECTEURMETIER
Insert into TSECTEURMETIER (TSMSECTGESTION,TSMMETIER) values ('SGMLEA','DIRCOM');


Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE)
values ('COMSGL','SGMLEA','DIRCOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

--

INSERT INTO TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) VALUES ('METIER','CONTENC','0');
INSERT INTO LANtusparam (TUSNOM, TUPCODE, LANCODE, TUPLIBELLE, TUPHELPTEXT) VALUES ('METIER','CONTENC','FR','Contentieux','null');
INSERT INTO FILTREPARAMPROFIL  VALUES ('CBI01','2','METIER','CONTENC','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('CBM01','2','METIER','CONTENC','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('AUT','2','METIER','CONTENC','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('TOUT','2','METIER','CONTENC','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('AUT02','2','METIER','CONTENC','0');

-------TSECTEURMETIER
Insert into TSECTEURMETIER (TSMSECTGESTION,TSMMETIER) values ('SGMLEA','CONTENC');


Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE)
values ('COMSGL','SGMLEA','CONTENC',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

--
INSERT INTO TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) VALUES ('METIER','GESCONT','0');
INSERT INTO LANtusparam (TUSNOM, TUPCODE, LANCODE, TUPLIBELLE, TUPHELPTEXT) VALUES ('METIER','GESREC','FR','Agent contentieux','null');
INSERT INTO FILTREPARAMPROFIL  VALUES ('CBI01','2','METIER','GESCONT','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('CBM01','2','METIER','GESCONT','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('AUT','2','METIER','GESCONT','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('TOUT','2','METIER','GESCONT','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('AUT02','2','METIER','GESCONT','0');

-------TSECTEURMETIER
Insert into TSECTEURMETIER (TSMSECTGESTION,TSMMETIER) values ('SGMLEA','GESCONT');


Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE)
values ('COMSGL','SGMLEA','GESCONT',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

commit ;
