----------EXT-212



---CRITERIA

Insert into CRITERIA (CRIID,CRICODE,CRITARGET,CRITABLETOSEARCH,CRICOLUMNTOSEARCH,CRILANDESCRIPTIONCOLUMN,CRIFUNCTION,CRIVALUETYPE,CRIFILTERCLAUSE,CRIPARAMETER,CRITABLESETTING,CRITARGETTABLE,CRITARGETCOLUMN,CRIFLAGCASSIOPAE,CRITABLETYPE)
values ('8531','AV_DC_RK','AVDOSS',null,null,null,'PAV4_CRITERIA.F_AV_DEC_RISK','STRING',null,null,null,null,null,null,null);

---LANCRITERIA

Insert into LANCRITERIA (LANCODE,CRIID,CRILABEL) values ('FR','8531','Decision availability Risk');

---- RULE

Insert into RULE (RULID,RULCODE,RULTARGET,RULOPERATOR,RULLOWERLIMIT,RULUPPERLIMIT,RULSTATUS,CRIIDFIRST,RULIDFIRST,RULIDSECOND,CRIIDSECONDMAX,CRIIDSECONDMIN,RULTYPE,RULFLAGCASSIOPAE,RULGROUP)
values ('3007162','AVISFA','AVDOSS','LIKE','DECIFA01',null,'ACTIVE','8531',null,null,null,null,'LOGICAL',null,null);

-----LANRULE

Insert into LANRULE (RULID,LANCODE,RULLABEL) values ('3007162','FR','avis favo');

----- CUSDEFDATA
Insert into CUSDEFDATA (CSEID,CDEORDRE,CDDORDRE,CDDSTRINGVALUE,CDDNUMERICVALUE,CDDDATEVALUE,CDDBOOLEANVALUE) values ('3','1','7','DECIFA01',null,null,null);

---- CDDRUL

Insert into CDDRUL (CSEID,CDEORDRE,CDDORDRE,RULID) values ('3','1','7','3007162');

update wstjump  set WSTORDERDEST =13  where  worcode = 'WFCLIPRO' AND WSTORDER=19    and rulid =4009  and WSTORDERDEST=10 ;

--- FORMALITE

Insert into FORMALITE (FORID,FORCODE,FORDEST,TACCODE,UGECODE,DOCIDEMIS,FORIDRAPPEL,FORDELAIEMIS,FORFLAGDOCEMIS,FORFLAGREPONSE,FORDELAIREP,FORFLAGFORRAPPEL,FORFLAGOBLIG,FORTYPEDATE,FORMODELANCEMENT,FORFLAGRECURRENT,FORPERIODE,FORMULTIPLE,FORJOUR,FORMOIS,FORDELAIREACTIVATION,FORDELAIREPONSEHEURE,FORNBACREER,FORTYPEJOUR,FORTYPERECURRENCE,FORPRIORITY,FORTYPE,FORPEREMIS,FORPERACT,FORPERREP,FORPERREPONSE,FORTYPEMSG,ANMID,FORTELTYPE,FORPROCEDURE,FORGROUP,CALID,FORGAPTYPE,TGRID,FORCLOSING,FORSTEPCODESOURCE,FORSTEPCODETARGET,FORFLAGREMINDER,FORREMMETHOD,FORREMPERIODBEFORE,FORREMMULTIPLEBEFORE,FORREMPERIODAFTER,FORREMMULTIPLEAFTER,FORPROCRUN,FORDTFREQUENCYTIME,FORWEIGHT,RMAID,SLAID,FORMESSAGE,FORTARGETTYPE,FOREXTERNALADDRESS,DMATYPE) 
values ('50054','50054','AVDOSS','GLOBAL','SGM',null,null,'0','0','2','1','0','0','DTIMME','EVT','0','J','0','0',null,'0',null,null,null,null,null,'GESTADM',null,null,null,null,null,null,null,null,null,'5','OUVRE',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

---- LANFORMALITE

Insert into LANFORMALITE (FORID,LANCODE,FORLIBELLE,FORDESCRIPTION) values ('50054','FR','Saisir Decision Finale DG',null);

---- FORDESTINATION

Insert into FORDESTINATION (FORID,TPGCODE,FDEORDRE,FDEULYSENDER,FDEUTICODESENDER,FDEGROCODESENDER,FDESECTGESTIONSENDER,FDEMETIERSENDER,FDEULYRECEIVER,FDEUTICODERECEIVER,FDEGROCODERECEIVER,FDESECTGESTIONRECEIVER,FDEMETIERRECEIVER,FDEACTION,FDEPRIORITY,FDEWORCODE,FDEWSTORDER,FDEWEIGHT,TCUCODE) 
values ('50054','TOUT','1',null,null,null,null,null,'GRORECEIVE',null,'DG_SGL','SGMLEA',null,null,null,null,null,null,null);

update wstconsequence set WSCACTIONCODE ='50054'  where  worcode = 'WFCLIPRO' AND WSTORDER=19 and wscorder=5  and WSCACTIONCODE ='30531' ;

update cddrul   set rulid =3007139 where cddordre=10195  and rulid =4013  ;


update wstjump  set WSTORDERDEST =10  where  worcode = 'WFCLIPRO' AND WSTORDER=13    and rulid =300762  and WSTORDERDEST=13 ;

update wstjump  set WSTORDERDEST =13  where  worcode = 'WFCLIPRO' AND WSTORDER=19    and rulid =4009  and WSTORDERDEST=10 ;

update wstjump  set rulid =4009  where worcode = 'WFCLIPRO' AND WSTORDER=13 and WSTORDERDEST =10 and rulid =300762 ;


delete  from wstjump   where  worcode = 'WFCLIPRO' AND wstorder=19 and WSTORDERDEST=13 ;

update wstjump  set rulid  =4009  where  worcode = 'WFCLIPRO' AND WSTORDER=19    and WSTORDERDEST=20 ;



update cddrul  set rulid =300760   where cddordre=10205 and cseid =108  and  rulid =1003  ;
update cddrul  set rulid =300761   where cddordre=10207 and cseid =108  and  rulid =1005  ;






commit ;





























