--------Nouvelle demande lot 1 --num7
------------Garantie CCG

--- AVTGARANTIE

Insert into AVTGARANTIE (TGACODE,ROLCODE,AGAFLAGMONTANT,AGAFLAGAUTO,AGAFLAGTXPRIME,AGAFLAGAUTOENGAGEMENT,AGAFLAGAUTOSIGNATURE,AGAFLAGAUTOFINANCING) 
values ('CCG','GARANT','1',null,null,null,null,null);


---- LANTGARANTIE

Insert into LANTGARANTIE (TGACODE,LANCODE,TGALIBELLE) values ('CCG','FR','Garantie CCG');

-----TGARANTIE

Insert into TGARANTIE (TGACODE,TGATYPE,TGAFLAGORFI,TGAFLAGRENOUVELLEMENT,TGAFLAGHORSBILAN,TGAFLAGINFOGARANT,TGATYPEDATEDEB,TGAFLAGBALE2,TGAFLAGADRESSE,TGADTDEBCONVENTION,TGADTFINCONVENTION,TGADTSIGNCONVENTION,TGATYPECONVENTION,TGANIVEAUINTERVENTION,TGANOMBRECONVENTION,TGAQPBASECONVENTION,TGAGARANTIEASSIETTE,TGADEPARTCOUVERTURE,TGAFLAGDIFFEREREG,TGAMISEENJEU,TGANBPERMISEENJEU,TGAPERIODEMISEENJEU,TGAPLAFONDRISQUE,TGANBPERIMPAYEDURABLE,TGAPERIODEIMPAYEDURABLE,TGAFLAGCREANCETTC,TGAROLLOVERMETHOD,TGAMAXROLLOVER,FORID,TGADISPLAYORDER) 
values ('CCG','AUTRE',null,null,null,null,null,'1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);

----- FILTREPARAMPROFIL

Insert into FILTREPARAMPROFIL (TPGCODE,FPPTYPE,FPPNOM,FPPCODE,FPPFLAGDEFAUT) values ('TOUT','0','AVTGARANTIE','CCG',null);
Insert into FILTREPARAMPROFIL (TPGCODE,FPPTYPE,FPPNOM,FPPCODE,FPPFLAGDEFAUT) values ('CBM01','0','AVTGARANTIE','CCG',null);
Insert into FILTREPARAMPROFIL (TPGCODE,FPPTYPE,FPPNOM,FPPCODE,FPPFLAGDEFAUT) values ('CBI01','0','AVTGARANTIE','CCG',null);
Insert into FILTREPARAMPROFIL (TPGCODE,FPPTYPE,FPPNOM,FPPCODE,FPPFLAGDEFAUT) values ('AUTCBM','0','AVTGARANTIE','CCG',null);
Insert into FILTREPARAMPROFIL (TPGCODE,FPPTYPE,FPPNOM,FPPCODE,FPPFLAGDEFAUT) values ('AUT','0','AVTGARANTIE','CCG',null);
Insert into FILTREPARAMPROFIL (TPGCODE,FPPTYPE,FPPNOM,FPPCODE,FPPFLAGDEFAUT) values ('AUT02','0','AVTGARANTIE','CCG',null);


commit ;
