-----EXTSGMAFOT-113
-------TPCTACCONTROLE

Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE)
 values ('U_U02','ACTEUR','GLOBAL','U_FFACT','3162','SGM',null,null);



-------LANTPCTACCONTROLE

Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) 
values ('U_U02','ACTEUR','GLOBAL','U_FFACT','FR','Impossible de rajouter pluisieurs adresses de facturation',null);


-----LKPHATTC

Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) 
values ('U_U02','ACTEUR','GLOBAL','U_FFACT','ACTIVE','ACTEUR','TOUT',null,null,'1',null);

Insert into LKPHATTC (TPCCODE,TPCDEST,TACCODE,TTCCODE,PHACODE,PHADEST,TPGCODE,PTCFLAGACTIF,PTCFLAGDEFAUT,PTCFLAGUSER,ALICODE) 
values ('U_U02','ACTEUR','GLOBAL','U_FFACT','INI','ACTEUR','TOUT','0',null,'1',null);

commit ;


