----------EXTSGMAFOT-243		
			  
----- TPCTACCONTROLE

Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','CBM','U_DVAL','3162','SGM',null,null);
Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','GLOBAL','U_DVAL','3162','SGM',null,null);
Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','CBI','U_DVAL','3162','SGM',null,null);
Insert into TPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,MSGID,UGECODE,RMAID,TTCTYPE) values ('U_DPR','AVDOSS','EMPRUNT','U_DVAL','3162','SGM',null,null);

  
  
------ LANTPCTACCONTROLE

Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO)
 values ('U_DPR','AVDOSS','GLOBAL','U_DVAL','FR','Tous les documents doivent etre validés',null);
Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO)
 values ('U_DPR','AVDOSS','CBM','U_DVAL','FR','Tous les documents doivent etre validés',null);
Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO) 
values ('U_DPR','AVDOSS','CBI','U_DVAL','FR','Tous les documents doivent etre validés',null);
Insert into LANTPCTACCONTROLE (TPCCODE,TPCDEST,TACCODE,TTCCODE,LANCODE,TTCLIBELLE,TTCMEMO)
 values ('U_DPR','AVDOSS','EMPRUNT','U_DVAL','FR','Tous les documents doivent etre validés',null);


/*------ LKTTCTEV

Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE) 
values ('CBI','AVDOSS','U_DPR','AVDOSS','U_DVAL','AVDOSS','EVF_TRANSFERT','CBI01','1',null,'1',null,null,null);
Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE) 
values ('CBM','AVDOSS','U_DPR','AVDOSS','U_DVAL','AVDOSS','EVF_TRANSFERT','AUT','1',null,'1',null,null,null);
Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE) 
values ('CBM','AVDOSS','U_DPR','AVDOSS','U_DVAL','AVDOSS','EVF_TRANSFERT','AUT02','1',null,'1',null,null,null);
Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE) 
values ('CBM','AVDOSS','U_DPR','AVDOSS','U_DVAL','AVDOSS','EVF_TRANSFERT','CBM01','1',null,'1',null,null,null);
Insert into LKTTCTEV (TACCODE,TEVDEST,TPCCODE,TPCDEST,TTCCODE,TMOMODULE,TMFFONCTION,TPGCODE,TCEFLAGACTIF,TCEFLAGDEFAUT,TCEFLAGUSER,TSTID,TCEFLAGUSERROLLBACK,ALICODE)
 values ('GLOBAL','AVDOSS','U_DPR','AVDOSS','U_DVAL','AVDOSS','EVF_TRANSFERT','TOUT','1',null,'1',null,null,null);
*/
	
---- WSTCONSEQUENCE

Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST)
 values ('WFCLICOM','7','5','CONTROLS','U_DVAL',null,null,null);

Insert into WSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,WSCACTIONTYPE,WSCACTIONCODE,WSCACTIONMODE,WSCFLAGMAIL,WORCODEDEST)
 values ('WFCLIPRO','10','5','CONTROLS','U_DVAL',null,null,null);

----- LANWSTCONSEQUENCE

Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLICOM','7','5','FR',null,null);

Insert into LANWSTCONSEQUENCE (WORCODE,WSTORDER,WSCORDER,LANCODE,WSTLABEL,WSTDESCRIPTION) values ('WFCLIPRO','10','5','FR',null,null);



commit ;
















				
				
				
				
				
				