

------Groups  

INSERT INTO GROUPE (GROCODE, GROINTITULE) VALUES ('CACOM','GRP COM CAFV');



------LKGROTACAGE
INSERT INTO lkgrotacage(Actid, taccode,grocode) VALUES ('2','CBM','CACOM');
INSERT INTO lkgrotacage(Actid, taccode,grocode) VALUES ('2','CBI','CACOM');
--------metier


INSERT INTO TUSPARAM (TUSNOM,TUPCODE,TUPFLAGORFI) VALUES ('METIER','CACOM','0');
INSERT INTO LANtusparam (TUSNOM, TUPCODE, LANCODE, TUPLIBELLE, TUPHELPTEXT) VALUES ('METIER','CACOM','FR','CAFV AND COMSGL','null');

update tusparam  set TUPFLAGORFI =null  where tusnom='METIER' and tupcode   in ( 'CACOM')  ;
update lantusparam  set TUPLIBELLE ='Chargé d''affaire et Commerciaux'  where tusnom='METIER' and tupcode   in ( 'CACOM')  ;

---filtrepafil

INSERT INTO FILTREPARAMPROFIL  VALUES ('CBI01','0','GROUPE','CACOM','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('CBM01','0','GROUPE','CACOM','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('AUT','0','GROUPE','CACOM','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('AUT02','0','GROUPE','CACOM','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('TOUT','0','GROUPE','CACOM','0');


INSERT INTO FILTREPARAMPROFIL  VALUES ('CBI01','2','METIER','CACOM','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('CBM01','2','METIER','CACOM','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('AUT','2','METIER','CACOM','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('TOUT','2','METIER','CACOM','0');
INSERT INTO FILTREPARAMPROFIL  VALUES ('AUT02','2','METIER','CACOM','0');

update FILTREPARAMPROFIL  set fppflagdefaut =null   where fppnom='METIER'  and fppcode in ('CACOM') ;

-------TSECTEURMETIER
Insert into TSECTEURMETIER (TSMSECTGESTION,TSMMETIER) values ('SGMLEA','CACOM');

------------
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('CAFV','SGMLEA','CACOM','0','0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,'0',null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('TARIKS','SGMLEA','CACOM','0','0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,'0',null,null,null,null,null,null);



Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('CASGL','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('AMINEB','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('JIHANEZ','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);


Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('KENZAL','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);



Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) values ('COMSGL','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) values ('COMDUP2','SGMLEA','CACOM',null,'0',null,null,null,null,null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) values ('TARIKSE','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) values ('COMDUP3','SGMLEA','CACOM',null,'0',null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) values ('ZAKARIAB','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) values ('COMSGLSUD','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) values ('COMSGLNORD','SGMLEA','CACOM','0','0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,'0',null,null,null,null,null,null);
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) values ('COMSGLEST','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) values ('COMSGLESTGE','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) values ('RACHIDN','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

commit ;
