----JALON ACTEUR & LAN 

Insert into JALON (JALCODE,JALFLAGINTERNE,JALCOLORPOS,JALCOLORFO,JALCOLORBO) values ('DECES','1',null,null,null);
Insert into JALON (JALCODE,JALFLAGINTERNE,JALCOLORPOS,JALCOLORFO,JALCOLORBO) values ('FUSION','1',null,null,null);
Insert into JALON (JALCODE,JALFLAGINTERNE,JALCOLORPOS,JALCOLORFO,JALCOLORBO) values ('LIQJUD','1',null,null,null);
Insert into JALON (JALCODE,JALFLAGINTERNE,JALCOLORPOS,JALCOLORFO,JALCOLORBO) values ('LIQUAMI','1',null,null,null);
Insert into JALON (JALCODE,JALFLAGINTERNE,JALCOLORPOS,JALCOLORFO,JALCOLORBO) values ('OUVERT','1',null,null,null);


Insert into LANJALON (JALCODE,LANCODE,JALLIBELLE,JALLIBELLEPOS) values ('DECES','FR','Décédé',null);
Insert into LANJALON (JALCODE,LANCODE,JALLIBELLE,JALLIBELLEPOS) values ('FUSION','FR','Dissous par fusion / absorbtion',null);
Insert into LANJALON (JALCODE,LANCODE,JALLIBELLE,JALLIBELLEPOS) values ('LIQJUD','FR','Liquidation judiciaire',null);
Insert into LANJALON (JALCODE,LANCODE,JALLIBELLE,JALLIBELLEPOS) values ('LIQUAMI','FR','Liquidation amiable',null);
Insert into LANJALON (JALCODE,LANCODE,JALLIBELLE,JALLIBELLEPOS) values ('OUVERT','FR','Nouveau',null);

