PROCEDURE S_ACTEUR_FULL(
        P_ACTID ACTEUR.ACTID%TYPE,
        PC_ACTEUR IN OUT T_CURSOR)
AS
    SRESIDENCE ACTTAB.ATBVALEUR%TYPE                   := NULL;
    STYPEACTEUR ACTTAB.ATBVALEUR%TYPE                  := NULL;
    NACTIDRELATION ACTEUR.ACTID%TYPE                   := NULL;
    SACTSECTGESTION ACTSECTGESTION.ACTSECTGESTION%TYPE := NULL;
    NACTIDSOCIETEGESTION NUMBER;
    SUGECODE ACTEUR.UGECODE%TYPE;
    SPHACODE ACTPHASE.PHACODE%TYPE;
BEGIN
    SUGECODE := PAV4_AVCOMMUN.F_UGECODE_ACTID(P_ACTID) ;
    BEGIN
        SELECT ACTSECTGESTION INTO SACTSECTGESTION FROM ACTSECTGESTION WHERE ACTID = P_ACTID;
EXCEPTION
WHEN OTHERS THEN
    NULL;
END;
BEGIN
    SELECT
        ACTIDGESTION
    INTO
        NACTIDSOCIETEGESTION
    FROM
        AROAGE
    WHERE
        ACTID          = P_ACTID
        AND AAGDTVALID =
        (
            SELECT MAX(AAGDTVALID) FROM AROAGE WHERE ACTID = P_ACTID
        )
        AND ROWNUM = 1;
EXCEPTION
WHEN OTHERS THEN
    NULL;
END;
BEGIN
    SELECT REPLACE(ATBVALEUR, '||', '') INTO SRESIDENCE FROM ACTTAB WHERE ACTID = P_ACTID AND TABCODE = '0R' AND ATBDTFIN IS NULL;
EXCEPTION
WHEN OTHERS THEN
    NULL;
END;
BEGIN
    SELECT REPLACE(ATBVALEUR, '||', '') INTO STYPEACTEUR FROM ACTTAB WHERE ACTID = P_ACTID AND TABCODE = '0E' AND ATBDTFIN IS NULL;
EXCEPTION
WHEN OTHERS THEN
    NULL;
END;
BEGIN
    SELECT ACTIDRELATION INTO NACTIDRELATION FROM ACTRELATION WHERE ACTID = P_ACTID AND TRECODE = PA_AVCOMMUN.F_GETCONSTANTE('GROUPE', SUGECODE) ;
EXCEPTION
WHEN OTHERS THEN
    BEGIN
        SELECT ACTIDRELATION INTO NACTIDRELATION FROM ACTRELATION WHERE ACTID = P_ACTID AND TRECODE = PA_AVCOMMUN.F_GETCONSTANTE('EMPLY', SUGECODE) ;
    EXCEPTION
    WHEN OTHERS THEN
        NULL;
    END;
END;
SELECT MAX(PHACODE) INTO SPHACODE FROM ACTPHASE WHERE ACTID = P_ACTID AND APHDTFIN IS NULL;
OPEN PC_ACTEUR FOR SELECT ACT.ACTID,
ACTRESIDENTCODE,
ACTFLAGTAXPROF,
ACTCAPITAL,
ACTFINMOISFISC,
ACTNUMRCM,
ACTLIBCOURT,
ACTNOM,
apaprenom,
Nvl( ACTNOM2,apaprenom) AS ACTNOM2,
ACTCODE,
ACT.CJUCODE,
ACT.NAFCODE,
ACT.LANCODE,
ACT.ACTTYPE,
ACT.ACTEIN,
UTICODECREAT,
UTICODEMAJ,
ACT.PAYCODE PAYCODE,
ACTSIRET,
ACTTVACE,
ACTCODERCM,
ACTMEMO,
ACTDTCREAT,
ACTDTMAJ,
DEVCODE,
ACTLIBCHEQUE,
ACTREGIMETVA,
SPHACODE,
ACT.DEVCODE,
NACTIDRELATION ACTIDRELATION,
SRESIDENCE BAFIRESIDENCE,
STYPEACTEUR BAFITYPEACTEUR,
ACT.UGECODE,
ACT.ACTIDSERVICING,
SACTSECTGESTION ACTSECTGESTION,
NACTIDSOCIETEGESTION ACTIDGESTION,
APADTNAISS,
APADEPTNAISS,
APACOMNAISS,
APANBENFANT,
APASEXE,
APAEMPLOYEUR,
APASITFAM,
APAFLAGPROPRIETE,
APATITRE,
APANOMMARITAL,
APAMIDDLENAME,
APAREGIMEMATRIM,
APAVILLENAISS,
APANOMPATRONYMIQUE,
APAFLAGINTERDITBANCAIRE,
APAPCTCAPITAL,
APAANEXPERACTIVITE,
APAANEXPERIENCEFONCTION,
APACODENIVEAUETUDE,
APAFLAGSUCCESSIONPRET,
APAFLAGHOMMECLE,
APACHGREGIMEMATRIM,
APAFLAGDIRIGEANT,
APADIRFONCTION,
APADTPERMISDECONDUIRE,
APA.PAYCODE APAPAYCODE,
ACTDTEXTHIRING,
ACTREPRESENTATIVE,
ACTTAXSYSTEM,
ACTRATTACHEMENT
 FROM ACTEUR ACT,
--                  ACTPHASE                APH,
ACTEURPARTICULIER APA WHERE ACT.ACTID = P_ACTID
--  AND     APH.ACTID = ACT.ACTID
--  AND             APH.APHDTFIN is null
AND ACT.ACTID = APA.ACTID (+);
END S_ACTEUR_FULL;