FUNCTION F_RESERVERNUMKSIOP
    (
        P_DOSID DOSSIERPROSPECT.DOSID%TYPE,
		P_DPRNUMERO		DOSSIERPROSPECT.DPRNUMERO%TYPE,
        P_TPGCODE TPROFILGESTION.TPGCODE%TYPE,
        P_ACTID ACTEUR.ACTID%TYPE,
        P_TPAPARAM TOPPARAM.TPAPARAM%TYPE,
        P_NUMCIBLE NUMERO.NUMCIBLE%TYPE,
        P_DATE DATE
    )
    RETURN VARCHAR2
AS
    DTFACTURE DATE                                  := P_DATE;
    BANNEE    NUMBER                                := NULL;
    BMOIS     NUMBER                                := NULL;
    NNUMERO NUMERO.NUMNUMERO%TYPE                   := - 1;
    NNEWNUM TOPPARAM.TPATEXTE%TYPE                  := NULL;
    SDEPARTMENT DOSSIERPROSPECT.DPRSECTGESTION%TYPE := NULL;
    NOPTIONSITEFACILITY NUMBER;
    STPAPARAM TOPPARAM.TPAPARAM%TYPE;
	nUseNumeroForDosNum number :=0;
BEGIN
    STPAPARAM   := P_TPAPARAM;
    
    IF STPAPARAM = 'DOSSIER' THEN
        SELECT
            SUBSTR(DPRSECTGESTION, 1, 3)
        INTO
            SDEPARTMENT
        FROM
            DOSSIERPROSPECT
        WHERE
            DOSID          = P_DOSID
            AND DPRVERSION =
            (
                SELECT DPRVERSION FROM V_DEAL VDE WHERE VDE.DOSID = P_DOSID
            ) ;
    END IF;
    CAS_PA_COMMON.S_NUMEROFORMATE(STPAPARAM, P_ACTID, -- ACTEUR.ACTID%TYPE (nSOCIETE)
    P_NUMCIBLE, -- NUMERO.NUMCIBLE%TYPE (nCIBLE)
    DTFACTURE, BANNEE, BMOIS, P_TPGCODE, SDEPARTMENT, NNUMERO, NNEWNUM) ;
	
	SELECT MAX(TPALOGIQUE) INTO nUseNumeroForDosNum FROM TOPPARAM WHERE TOPTABLE='AVDOSS' AND TPAPARAM='USENUMEROFORDOSNUM';
	If nUseNumeroForDosNum != 1 THEN
		nNewNum := PA_GENERER_NUMEROS_CASSIOPEE.F_GENERER_DPRNUMCASSIOPEE( P_DOSID, P_DPRNUMERO, P_TPGCODE, nNewNum );
	 update numero@SGM_LINK set NUMNUMERO=to_number(nNewNum ) where numcible ='DOSNUM';
  end if;
  
    RETURN  NNEWNUM  ; 
END F_RESERVERNUMKSIOP;