---SOGELEASE-206: Tâche encore disponible pour le profil RMCP alors que la proposition est transférée au BO ---
Insert into RULE (RULID,RULCODE,RULTARGET,RULOPERATOR,RULLOWERLIMIT,RULUPPERLIMIT,RULSTATUS,CRIIDFIRST,RULIDFIRST,RULIDSECOND,CRIIDSECONDMAX,CRIIDSECONDMIN,RULTYPE,RULFLAGCASSIOPAE,RULGROUP) values ('3007182','CFORRMCP','AVDOSS','<','5',null,'ACTIVE','8520',null,null,null,null,'LOGICAL',null,null);
Insert into LANRULE (RULID,LANCODE,RULLABEL) values ('3007182','FR','Close formalite RMCP');
Insert into RULE (RULID,RULCODE,RULTARGET,RULOPERATOR,RULLOWERLIMIT,RULUPPERLIMIT,RULSTATUS,CRIIDFIRST,RULIDFIRST,RULIDSECOND,CRIIDSECONDMAX,CRIIDSECONDMIN,RULTYPE,RULFLAGCASSIOPAE,RULGROUP) values ('3007183','CFORRMCP7','AVDOSS','IN',null,null,'ACTIVE','3',null,null,null,null,'LOGICAL',null,null);
Insert into LANRULE (RULID,LANCODE,RULLABEL) values ('3007183','FR','Close formalite RMCP 7');
Insert into RULVALUE (RULID,RVAORDRE,RVAVALUE,RULIDVALUE,CRIID) values ('3007183','1',null,'3007182',null);
Insert into RULVALUE (RULID,RVAORDRE,RVAVALUE,RULIDVALUE,CRIID) values ('3007183','2',null,'1003',null);
update cddrul set RULID = '3007183' where CDDORDRE = 10811;


COMMIT;