
update  fordestination   set     FDEULYRECEIVER='METIER'  
 where forid  in (select forid from fordestination   where   FDEULYRECEIVER='JOB' and fdemetierreceiver='CACOM' and fdeordre =1) ;


commit ;

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('OUMAIMA','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('ALIM','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('MHAMEDB','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('SARAH','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('MOHAMEDAF','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('RAJAAA','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('IJLALS','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('MOHAMEDG','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('BADREIR','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('HICHAMB','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);


Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('SALAHM','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);


Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('YOUSRAS','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);


Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('NABILM','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);
Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('ANOUARB','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('ISMAILT','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('OMARB','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);

Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('MEHDIMI','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);


Insert into UTITSM (UTICODE,TSMSECTGESTION,TSMMETIER,TSMFLAGSUPERVISEUR,TSMFLAGDEFAUT,TSMPARTNAME,TSMCOUNGR,TSMCOUNEGE,TSMDTSTART,TSMDTEND,TSMINCOMINGPATH,TSMFLAGLEADER,TSMSALESNETWORK,TSMTEAMCODE,TSMMAXASSIGN,ACTID,TSMSTATUS,TSMSUPERVISORTYPE) 
values ('KHALIDA','SGMLEA','CACOM',null,'0',null,null,null,to_date('30/01/18','DD/MM/RR'),null,null,null,null,null,null,null,null,null);


commit ;
